// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum/battle_result.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Neon.Model.Api.Enum {

  /// <summary>Holder for reflection information generated from enum/battle_result.proto</summary>
  public static partial class BattleResultReflection {

    #region Descriptor
    /// <summary>File descriptor for enum/battle_result.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BattleResultReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhlbnVtL2JhdHRsZV9yZXN1bHQucHJvdG8SCW5lb24uZW51bRoYZXh0ZW5z",
            "aW9uL2VsaXhpcnBiLnByb3RvKi0KDEJhdHRsZVJlc3VsdBIHCgN3b24QABII",
            "CgRsb3N0EAESCgoGcmV0aXJlEAJCJ6oCE05lb24uTW9kZWwuQXBpLkVudW26",
            "QQ4KDE5lb24uUEIuRW51bWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ApiClient.Extension.ElixirpbReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Neon.Model.Api.Enum.BattleResult), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum BattleResult {
    [pbr::OriginalName("won")] Won = 0,
    [pbr::OriginalName("lost")] Lost = 1,
    [pbr::OriginalName("retire")] Retire = 2,
  }

  #endregion

}

#endregion Designer generated code
