// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum/battle_task_topic_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Neon.Model.Api.Enum {

  /// <summary>Holder for reflection information generated from enum/battle_task_topic_type.proto</summary>
  public static partial class BattleTaskTopicTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum/battle_task_topic_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BattleTaskTopicTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFlbnVtL2JhdHRsZV90YXNrX3RvcGljX3R5cGUucHJvdG8SCW5lb24uZW51",
            "bRoYZXh0ZW5zaW9uL2VsaXhpcnBiLnByb3RvKtwBChNCYXR0bGVUYXNrVG9w",
            "aWNUeXBlEhMKD2F0dGFjaF9wcmVzc3VyZRAAEhYKEmF0dGFjaF91bmZvcnRp",
            "ZmllZBABEhIKDnNoYXJrX2VhdF9taW5lEAISCwoHaGVhbF9ocBADEhkKFWJy",
            "YXZlX2RpdmVyX2JyZWFrX2xlZxAEEhIKDnNwZWNpYWxfYXR0YWNrEAUSBwoD",
            "cXRlEAYSEQoNYXR0YWNoX3NjYXJlZBAHEhMKD2F0dGFjaF9lbGVjdHJpYxAI",
            "EhcKE2hpdF9iYWNrX3RvX2V5ZWJhbGwQCUInqgITTmVvbi5Nb2RlbC5BcGku",
            "RW51bbpBDgoMTmVvbi5QQi5FbnVtYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ApiClient.Extension.ElixirpbReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Neon.Model.Api.Enum.BattleTaskTopicType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum BattleTaskTopicType {
    [pbr::OriginalName("attach_pressure")] AttachPressure = 0,
    [pbr::OriginalName("attach_unfortified")] AttachUnfortified = 1,
    [pbr::OriginalName("shark_eat_mine")] SharkEatMine = 2,
    [pbr::OriginalName("heal_hp")] HealHp = 3,
    [pbr::OriginalName("brave_diver_break_leg")] BraveDiverBreakLeg = 4,
    [pbr::OriginalName("special_attack")] SpecialAttack = 5,
    [pbr::OriginalName("qte")] Qte = 6,
    [pbr::OriginalName("attach_scared")] AttachScared = 7,
    [pbr::OriginalName("attach_electric")] AttachElectric = 8,
    [pbr::OriginalName("hit_back_to_eyeball")] HitBackToEyeball = 9,
  }

  #endregion

}

#endregion Designer generated code
