// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum/quest_result.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Neon.Model.Api.Enum {

  /// <summary>Holder for reflection information generated from enum/quest_result.proto</summary>
  public static partial class QuestResultReflection {

    #region Descriptor
    /// <summary>File descriptor for enum/quest_result.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QuestResultReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdlbnVtL3F1ZXN0X3Jlc3VsdC5wcm90bxIJbmVvbi5lbnVtGhhleHRlbnNp",
            "b24vZWxpeGlycGIucHJvdG8qJgoLUXVlc3RSZXN1bHQSCwoHY2xlYXJlZBAA",
            "EgoKBmZhaWxlZBABQieqAhNOZW9uLk1vZGVsLkFwaS5FbnVtukEOCgxOZW9u",
            "LlBCLkVudW1iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ApiClient.Extension.ElixirpbReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Neon.Model.Api.Enum.QuestResult), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum QuestResult {
    [pbr::OriginalName("cleared")] Cleared = 0,
    [pbr::OriginalName("failed")] Failed = 1,
  }

  #endregion

}

#endregion Designer generated code
