// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum/stamina_recovery_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Neon.Model.Api.Enum {

  /// <summary>Holder for reflection information generated from enum/stamina_recovery_type.proto</summary>
  public static partial class StaminaRecoveryTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum/stamina_recovery_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StaminaRecoveryTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBlbnVtL3N0YW1pbmFfcmVjb3ZlcnlfdHlwZS5wcm90bxIJbmVvbi5lbnVt",
            "GhhleHRlbnNpb24vZWxpeGlycGIucHJvdG8qPwoTU3RhbWluYVJlY292ZXJ5",
            "VHlwZRIQCgxub25fcmVjb3ZlcnkQABIMCghwdXJjaGFzZRABEggKBGl0ZW0Q",
            "AkInqgITTmVvbi5Nb2RlbC5BcGkuRW51bbpBDgoMTmVvbi5QQi5FbnVtYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ApiClient.Extension.ElixirpbReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Neon.Model.Api.Enum.StaminaRecoveryType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum StaminaRecoveryType {
    [pbr::OriginalName("non_recovery")] NonRecovery = 0,
    [pbr::OriginalName("purchase")] Purchase = 1,
    [pbr::OriginalName("item")] Item = 2,
  }

  #endregion

}

#endregion Designer generated code
