// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: model/cycle_update_shop_state.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Neon.Model.Api.Model {

  /// <summary>Holder for reflection information generated from model/cycle_update_shop_state.proto</summary>
  public static partial class CycleUpdateShopStateReflection {

    #region Descriptor
    /// <summary>File descriptor for model/cycle_update_shop_state.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CycleUpdateShopStateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNtb2RlbC9jeWNsZV91cGRhdGVfc2hvcF9zdGF0ZS5wcm90bxIKbmVvbi5t",
            "b2RlbBoYZXh0ZW5zaW9uL2VsaXhpcnBiLnByb3RvGh9nb29nbGUvcHJvdG9i",
            "dWYvdGltZXN0YW1wLnByb3RvIpkBChRDeWNsZVVwZGF0ZVNob3BTdGF0ZRIc",
            "ChRjeWNsZV91cGRhdGVfc2hvcF9pZBgBIAEoBRITCgtpc19yZWxlYXNlZBgE",
            "IAEoCBIXCg9wdXJjaGFzZWRfY291bnQYAiABKAUSNQoRbGFzdF9wdXJjaGFz",
            "ZWRfYXQYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQimqAhRO",
            "ZW9uLk1vZGVsLkFwaS5Nb2RlbLpBDwoNTmVvbi5QQi5Nb2RlbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ApiClient.Extension.ElixirpbReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Model.CycleUpdateShopState), global::Neon.Model.Api.Model.CycleUpdateShopState.Parser, new[]{ "CycleUpdateShopId", "IsReleased", "PurchasedCount", "LastPurchasedAt" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CycleUpdateShopState : pb::IMessage<CycleUpdateShopState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CycleUpdateShopState> _parser = new pb::MessageParser<CycleUpdateShopState>(() => new CycleUpdateShopState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CycleUpdateShopState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Model.CycleUpdateShopStateReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CycleUpdateShopState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CycleUpdateShopState(CycleUpdateShopState other) : this() {
      cycleUpdateShopId_ = other.cycleUpdateShopId_;
      isReleased_ = other.isReleased_;
      purchasedCount_ = other.purchasedCount_;
      lastPurchasedAt_ = other.lastPurchasedAt_ != null ? other.lastPurchasedAt_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CycleUpdateShopState Clone() {
      return new CycleUpdateShopState(this);
    }

    /// <summary>Field number for the "cycle_update_shop_id" field.</summary>
    public const int CycleUpdateShopIdFieldNumber = 1;
    private int cycleUpdateShopId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CycleUpdateShopId {
      get { return cycleUpdateShopId_; }
      set {
        cycleUpdateShopId_ = value;
      }
    }

    /// <summary>Field number for the "is_released" field.</summary>
    public const int IsReleasedFieldNumber = 4;
    private bool isReleased_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsReleased {
      get { return isReleased_; }
      set {
        isReleased_ = value;
      }
    }

    /// <summary>Field number for the "purchased_count" field.</summary>
    public const int PurchasedCountFieldNumber = 2;
    private int purchasedCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PurchasedCount {
      get { return purchasedCount_; }
      set {
        purchasedCount_ = value;
      }
    }

    /// <summary>Field number for the "last_purchased_at" field.</summary>
    public const int LastPurchasedAtFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp lastPurchasedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp LastPurchasedAt {
      get { return lastPurchasedAt_; }
      set {
        lastPurchasedAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CycleUpdateShopState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CycleUpdateShopState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CycleUpdateShopId != other.CycleUpdateShopId) return false;
      if (IsReleased != other.IsReleased) return false;
      if (PurchasedCount != other.PurchasedCount) return false;
      if (!object.Equals(LastPurchasedAt, other.LastPurchasedAt)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CycleUpdateShopId != 0) hash ^= CycleUpdateShopId.GetHashCode();
      if (IsReleased != false) hash ^= IsReleased.GetHashCode();
      if (PurchasedCount != 0) hash ^= PurchasedCount.GetHashCode();
      if (lastPurchasedAt_ != null) hash ^= LastPurchasedAt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CycleUpdateShopId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(CycleUpdateShopId);
      }
      if (PurchasedCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PurchasedCount);
      }
      if (lastPurchasedAt_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(LastPurchasedAt);
      }
      if (IsReleased != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsReleased);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CycleUpdateShopId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(CycleUpdateShopId);
      }
      if (PurchasedCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PurchasedCount);
      }
      if (lastPurchasedAt_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(LastPurchasedAt);
      }
      if (IsReleased != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsReleased);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CycleUpdateShopId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CycleUpdateShopId);
      }
      if (IsReleased != false) {
        size += 1 + 1;
      }
      if (PurchasedCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PurchasedCount);
      }
      if (lastPurchasedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LastPurchasedAt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CycleUpdateShopState other) {
      if (other == null) {
        return;
      }
      if (other.CycleUpdateShopId != 0) {
        CycleUpdateShopId = other.CycleUpdateShopId;
      }
      if (other.IsReleased != false) {
        IsReleased = other.IsReleased;
      }
      if (other.PurchasedCount != 0) {
        PurchasedCount = other.PurchasedCount;
      }
      if (other.lastPurchasedAt_ != null) {
        if (lastPurchasedAt_ == null) {
          LastPurchasedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        LastPurchasedAt.MergeFrom(other.LastPurchasedAt);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CycleUpdateShopId = input.ReadInt32();
            break;
          }
          case 16: {
            PurchasedCount = input.ReadInt32();
            break;
          }
          case 26: {
            if (lastPurchasedAt_ == null) {
              LastPurchasedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(LastPurchasedAt);
            break;
          }
          case 32: {
            IsReleased = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CycleUpdateShopId = input.ReadInt32();
            break;
          }
          case 16: {
            PurchasedCount = input.ReadInt32();
            break;
          }
          case 26: {
            if (lastPurchasedAt_ == null) {
              LastPurchasedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(LastPurchasedAt);
            break;
          }
          case 32: {
            IsReleased = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
