// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: model/login_bonus.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Neon.Model.Api.Model {

  /// <summary>Holder for reflection information generated from model/login_bonus.proto</summary>
  public static partial class LoginBonusReflection {

    #region Descriptor
    /// <summary>File descriptor for model/login_bonus.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LoginBonusReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chdtb2RlbC9sb2dpbl9ib251cy5wcm90bxIKbmVvbi5tb2RlbBoYZXh0ZW5z",
            "aW9uL2VsaXhpcnBiLnByb3RvIlEKCkxvZ2luQm9udXMSFgoObG9naW5fYm9u",
            "dXNfaWQYASABKAUSFAoMcmVjZWl2ZWRfZGF5GAIgASgFEhUKDWxvZ2dlZF9p",
            "bl9kYXkYAyABKAVCKaoCFE5lb24uTW9kZWwuQXBpLk1vZGVsukEPCg1OZW9u",
            "LlBCLk1vZGVsYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ApiClient.Extension.ElixirpbReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Model.LoginBonus), global::Neon.Model.Api.Model.LoginBonus.Parser, new[]{ "LoginBonusId", "ReceivedDay", "LoggedInDay" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LoginBonus : pb::IMessage<LoginBonus>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LoginBonus> _parser = new pb::MessageParser<LoginBonus>(() => new LoginBonus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LoginBonus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Model.LoginBonusReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginBonus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginBonus(LoginBonus other) : this() {
      loginBonusId_ = other.loginBonusId_;
      receivedDay_ = other.receivedDay_;
      loggedInDay_ = other.loggedInDay_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginBonus Clone() {
      return new LoginBonus(this);
    }

    /// <summary>Field number for the "login_bonus_id" field.</summary>
    public const int LoginBonusIdFieldNumber = 1;
    private int loginBonusId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LoginBonusId {
      get { return loginBonusId_; }
      set {
        loginBonusId_ = value;
      }
    }

    /// <summary>Field number for the "received_day" field.</summary>
    public const int ReceivedDayFieldNumber = 2;
    private int receivedDay_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ReceivedDay {
      get { return receivedDay_; }
      set {
        receivedDay_ = value;
      }
    }

    /// <summary>Field number for the "logged_in_day" field.</summary>
    public const int LoggedInDayFieldNumber = 3;
    private int loggedInDay_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LoggedInDay {
      get { return loggedInDay_; }
      set {
        loggedInDay_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LoginBonus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LoginBonus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LoginBonusId != other.LoginBonusId) return false;
      if (ReceivedDay != other.ReceivedDay) return false;
      if (LoggedInDay != other.LoggedInDay) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LoginBonusId != 0) hash ^= LoginBonusId.GetHashCode();
      if (ReceivedDay != 0) hash ^= ReceivedDay.GetHashCode();
      if (LoggedInDay != 0) hash ^= LoggedInDay.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LoginBonusId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(LoginBonusId);
      }
      if (ReceivedDay != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ReceivedDay);
      }
      if (LoggedInDay != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(LoggedInDay);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LoginBonusId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(LoginBonusId);
      }
      if (ReceivedDay != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ReceivedDay);
      }
      if (LoggedInDay != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(LoggedInDay);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LoginBonusId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LoginBonusId);
      }
      if (ReceivedDay != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReceivedDay);
      }
      if (LoggedInDay != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LoggedInDay);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LoginBonus other) {
      if (other == null) {
        return;
      }
      if (other.LoginBonusId != 0) {
        LoginBonusId = other.LoginBonusId;
      }
      if (other.ReceivedDay != 0) {
        ReceivedDay = other.ReceivedDay;
      }
      if (other.LoggedInDay != 0) {
        LoggedInDay = other.LoggedInDay;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LoginBonusId = input.ReadInt32();
            break;
          }
          case 16: {
            ReceivedDay = input.ReadInt32();
            break;
          }
          case 24: {
            LoggedInDay = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LoginBonusId = input.ReadInt32();
            break;
          }
          case 16: {
            ReceivedDay = input.ReadInt32();
            break;
          }
          case 24: {
            LoggedInDay = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
