// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: model/refund_application.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Neon.Model.Api.Model {

  /// <summary>Holder for reflection information generated from model/refund_application.proto</summary>
  public static partial class RefundApplicationReflection {

    #region Descriptor
    /// <summary>File descriptor for model/refund_application.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RefundApplicationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5tb2RlbC9yZWZ1bmRfYXBwbGljYXRpb24ucHJvdG8SCm5lb24ubW9kZWwa",
            "GGV4dGVuc2lvbi9lbGl4aXJwYi5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3Rp",
            "bWVzdGFtcC5wcm90byKZAQoRUmVmdW5kQXBwbGljYXRpb24SGQoRdmVyaWZp",
            "ZWRfZW1haWxfaWQYAyABKAkSOAoUZW1haWxfaWRfdmVyaWZpZWRfYXQYASAB",
            "KAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi8KC2FjY2VwdGVkX2F0",
            "GAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIpqgIUTmVvbi5N",
            "b2RlbC5BcGkuTW9kZWy6QQ8KDU5lb24uUEIuTW9kZWxiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ApiClient.Extension.ElixirpbReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Model.RefundApplication), global::Neon.Model.Api.Model.RefundApplication.Parser, new[]{ "VerifiedEmailId", "EmailIdVerifiedAt", "AcceptedAt" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RefundApplication : pb::IMessage<RefundApplication>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RefundApplication> _parser = new pb::MessageParser<RefundApplication>(() => new RefundApplication());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RefundApplication> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Model.RefundApplicationReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RefundApplication() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RefundApplication(RefundApplication other) : this() {
      verifiedEmailId_ = other.verifiedEmailId_;
      emailIdVerifiedAt_ = other.emailIdVerifiedAt_ != null ? other.emailIdVerifiedAt_.Clone() : null;
      acceptedAt_ = other.acceptedAt_ != null ? other.acceptedAt_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RefundApplication Clone() {
      return new RefundApplication(this);
    }

    /// <summary>Field number for the "verified_email_id" field.</summary>
    public const int VerifiedEmailIdFieldNumber = 3;
    private string verifiedEmailId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string VerifiedEmailId {
      get { return verifiedEmailId_; }
      set {
        verifiedEmailId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "email_id_verified_at" field.</summary>
    public const int EmailIdVerifiedAtFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp emailIdVerifiedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp EmailIdVerifiedAt {
      get { return emailIdVerifiedAt_; }
      set {
        emailIdVerifiedAt_ = value;
      }
    }

    /// <summary>Field number for the "accepted_at" field.</summary>
    public const int AcceptedAtFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp acceptedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp AcceptedAt {
      get { return acceptedAt_; }
      set {
        acceptedAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RefundApplication);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RefundApplication other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (VerifiedEmailId != other.VerifiedEmailId) return false;
      if (!object.Equals(EmailIdVerifiedAt, other.EmailIdVerifiedAt)) return false;
      if (!object.Equals(AcceptedAt, other.AcceptedAt)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (VerifiedEmailId.Length != 0) hash ^= VerifiedEmailId.GetHashCode();
      if (emailIdVerifiedAt_ != null) hash ^= EmailIdVerifiedAt.GetHashCode();
      if (acceptedAt_ != null) hash ^= AcceptedAt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (emailIdVerifiedAt_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(EmailIdVerifiedAt);
      }
      if (acceptedAt_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AcceptedAt);
      }
      if (VerifiedEmailId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(VerifiedEmailId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (emailIdVerifiedAt_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(EmailIdVerifiedAt);
      }
      if (acceptedAt_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AcceptedAt);
      }
      if (VerifiedEmailId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(VerifiedEmailId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (VerifiedEmailId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VerifiedEmailId);
      }
      if (emailIdVerifiedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EmailIdVerifiedAt);
      }
      if (acceptedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AcceptedAt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RefundApplication other) {
      if (other == null) {
        return;
      }
      if (other.VerifiedEmailId.Length != 0) {
        VerifiedEmailId = other.VerifiedEmailId;
      }
      if (other.emailIdVerifiedAt_ != null) {
        if (emailIdVerifiedAt_ == null) {
          EmailIdVerifiedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        EmailIdVerifiedAt.MergeFrom(other.EmailIdVerifiedAt);
      }
      if (other.acceptedAt_ != null) {
        if (acceptedAt_ == null) {
          AcceptedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        AcceptedAt.MergeFrom(other.AcceptedAt);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (emailIdVerifiedAt_ == null) {
              EmailIdVerifiedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(EmailIdVerifiedAt);
            break;
          }
          case 18: {
            if (acceptedAt_ == null) {
              AcceptedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(AcceptedAt);
            break;
          }
          case 26: {
            VerifiedEmailId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (emailIdVerifiedAt_ == null) {
              EmailIdVerifiedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(EmailIdVerifiedAt);
            break;
          }
          case 18: {
            if (acceptedAt_ == null) {
              AcceptedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(AcceptedAt);
            break;
          }
          case 26: {
            VerifiedEmailId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
