// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: model/shop_product_state.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Neon.Model.Api.Model {

  /// <summary>Holder for reflection information generated from model/shop_product_state.proto</summary>
  public static partial class ShopProductStateReflection {

    #region Descriptor
    /// <summary>File descriptor for model/shop_product_state.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ShopProductStateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5tb2RlbC9zaG9wX3Byb2R1Y3Rfc3RhdGUucHJvdG8SCm5lb24ubW9kZWwa",
            "GGV4dGVuc2lvbi9lbGl4aXJwYi5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3Rp",
            "bWVzdGFtcC5wcm90byJ3ChBTaG9wUHJvZHVjdFN0YXRlEhcKD3Nob3BfcHJv",
            "ZHVjdF9pZBgBIAEoBRIXCg9wdXJjaGFzZWRfY291bnQYAiABKAUSMQoNbmV4",
            "dF9yZXNldF9hdBgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBC",
            "KaoCFE5lb24uTW9kZWwuQXBpLk1vZGVsukEPCg1OZW9uLlBCLk1vZGVsYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ApiClient.Extension.ElixirpbReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Model.ShopProductState), global::Neon.Model.Api.Model.ShopProductState.Parser, new[]{ "ShopProductId", "PurchasedCount", "NextResetAt" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ShopProductState : pb::IMessage<ShopProductState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ShopProductState> _parser = new pb::MessageParser<ShopProductState>(() => new ShopProductState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ShopProductState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Model.ShopProductStateReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShopProductState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShopProductState(ShopProductState other) : this() {
      shopProductId_ = other.shopProductId_;
      purchasedCount_ = other.purchasedCount_;
      nextResetAt_ = other.nextResetAt_ != null ? other.nextResetAt_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShopProductState Clone() {
      return new ShopProductState(this);
    }

    /// <summary>Field number for the "shop_product_id" field.</summary>
    public const int ShopProductIdFieldNumber = 1;
    private int shopProductId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ShopProductId {
      get { return shopProductId_; }
      set {
        shopProductId_ = value;
      }
    }

    /// <summary>Field number for the "purchased_count" field.</summary>
    public const int PurchasedCountFieldNumber = 2;
    private int purchasedCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PurchasedCount {
      get { return purchasedCount_; }
      set {
        purchasedCount_ = value;
      }
    }

    /// <summary>Field number for the "next_reset_at" field.</summary>
    public const int NextResetAtFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp nextResetAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp NextResetAt {
      get { return nextResetAt_; }
      set {
        nextResetAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ShopProductState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ShopProductState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ShopProductId != other.ShopProductId) return false;
      if (PurchasedCount != other.PurchasedCount) return false;
      if (!object.Equals(NextResetAt, other.NextResetAt)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ShopProductId != 0) hash ^= ShopProductId.GetHashCode();
      if (PurchasedCount != 0) hash ^= PurchasedCount.GetHashCode();
      if (nextResetAt_ != null) hash ^= NextResetAt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ShopProductId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ShopProductId);
      }
      if (PurchasedCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PurchasedCount);
      }
      if (nextResetAt_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(NextResetAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ShopProductId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ShopProductId);
      }
      if (PurchasedCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PurchasedCount);
      }
      if (nextResetAt_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(NextResetAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ShopProductId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ShopProductId);
      }
      if (PurchasedCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PurchasedCount);
      }
      if (nextResetAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NextResetAt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ShopProductState other) {
      if (other == null) {
        return;
      }
      if (other.ShopProductId != 0) {
        ShopProductId = other.ShopProductId;
      }
      if (other.PurchasedCount != 0) {
        PurchasedCount = other.PurchasedCount;
      }
      if (other.nextResetAt_ != null) {
        if (nextResetAt_ == null) {
          NextResetAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        NextResetAt.MergeFrom(other.NextResetAt);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ShopProductId = input.ReadInt32();
            break;
          }
          case 16: {
            PurchasedCount = input.ReadInt32();
            break;
          }
          case 26: {
            if (nextResetAt_ == null) {
              NextResetAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(NextResetAt);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ShopProductId = input.ReadInt32();
            break;
          }
          case 16: {
            PurchasedCount = input.ReadInt32();
            break;
          }
          case 26: {
            if (nextResetAt_ == null) {
              NextResetAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(NextResetAt);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
