// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: model/store_product.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Neon.Model.Api.Model {

  /// <summary>Holder for reflection information generated from model/store_product.proto</summary>
  public static partial class StoreProductReflection {

    #region Descriptor
    /// <summary>File descriptor for model/store_product.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StoreProductReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chltb2RlbC9zdG9yZV9wcm9kdWN0LnByb3RvEgpuZW9uLm1vZGVsGhhleHRl",
            "bnNpb24vZWxpeGlycGIucHJvdG8aHmdvb2dsZS9wcm90b2J1Zi93cmFwcGVy",
            "cy5wcm90byLUAQoMU3RvcmVQcm9kdWN0EgoKAmlkGAYgASgFEjAKCnByb2R1",
            "Y3RfaWQYASABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSFAoM",
            "bW9uZXlfYW1vdW50GAIgASgFEhMKC2ZyZWVfYW1vdW50GAMgASgFEisKBXBy",
            "aWNlGAQgASgLMhwuZ29vZ2xlLnByb3RvYnVmLkRvdWJsZVZhbHVlEi4KCGN1",
            "cnJlbmN5GAUgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlQimq",
            "AhROZW9uLk1vZGVsLkFwaS5Nb2RlbLpBDwoNTmVvbi5QQi5Nb2RlbGIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ApiClient.Extension.ElixirpbReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Model.StoreProduct), global::Neon.Model.Api.Model.StoreProduct.Parser, new[]{ "Id", "ProductId", "MoneyAmount", "FreeAmount", "Price", "Currency" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class StoreProduct : pb::IMessage<StoreProduct>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StoreProduct> _parser = new pb::MessageParser<StoreProduct>(() => new StoreProduct());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StoreProduct> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Model.StoreProductReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StoreProduct() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StoreProduct(StoreProduct other) : this() {
      id_ = other.id_;
      ProductId = other.ProductId;
      moneyAmount_ = other.moneyAmount_;
      freeAmount_ = other.freeAmount_;
      Price = other.Price;
      Currency = other.Currency;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StoreProduct Clone() {
      return new StoreProduct(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 6;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "product_id" field.</summary>
    public const int ProductIdFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _single_productId_codec = pb::FieldCodec.ForClassWrapper<string>(10);
    private string productId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ProductId {
      get { return productId_; }
      set {
        productId_ = value;
      }
    }


    /// <summary>Field number for the "money_amount" field.</summary>
    public const int MoneyAmountFieldNumber = 2;
    private int moneyAmount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MoneyAmount {
      get { return moneyAmount_; }
      set {
        moneyAmount_ = value;
      }
    }

    /// <summary>Field number for the "free_amount" field.</summary>
    public const int FreeAmountFieldNumber = 3;
    private int freeAmount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FreeAmount {
      get { return freeAmount_; }
      set {
        freeAmount_ = value;
      }
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 4;
    private static readonly pb::FieldCodec<double?> _single_price_codec = pb::FieldCodec.ForStructWrapper<double>(34);
    private double? price_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double? Price {
      get { return price_; }
      set {
        price_ = value;
      }
    }


    /// <summary>Field number for the "currency" field.</summary>
    public const int CurrencyFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _single_currency_codec = pb::FieldCodec.ForClassWrapper<string>(42);
    private string currency_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Currency {
      get { return currency_; }
      set {
        currency_ = value;
      }
    }


    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StoreProduct);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StoreProduct other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (ProductId != other.ProductId) return false;
      if (MoneyAmount != other.MoneyAmount) return false;
      if (FreeAmount != other.FreeAmount) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseNullableDoubleEqualityComparer.Equals(Price, other.Price)) return false;
      if (Currency != other.Currency) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (productId_ != null) hash ^= ProductId.GetHashCode();
      if (MoneyAmount != 0) hash ^= MoneyAmount.GetHashCode();
      if (FreeAmount != 0) hash ^= FreeAmount.GetHashCode();
      if (price_ != null) hash ^= pbc::ProtobufEqualityComparers.BitwiseNullableDoubleEqualityComparer.GetHashCode(Price);
      if (currency_ != null) hash ^= Currency.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (productId_ != null) {
        _single_productId_codec.WriteTagAndValue(output, ProductId);
      }
      if (MoneyAmount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(MoneyAmount);
      }
      if (FreeAmount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(FreeAmount);
      }
      if (price_ != null) {
        _single_price_codec.WriteTagAndValue(output, Price);
      }
      if (currency_ != null) {
        _single_currency_codec.WriteTagAndValue(output, Currency);
      }
      if (Id != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (productId_ != null) {
        _single_productId_codec.WriteTagAndValue(ref output, ProductId);
      }
      if (MoneyAmount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(MoneyAmount);
      }
      if (FreeAmount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(FreeAmount);
      }
      if (price_ != null) {
        _single_price_codec.WriteTagAndValue(ref output, Price);
      }
      if (currency_ != null) {
        _single_currency_codec.WriteTagAndValue(ref output, Currency);
      }
      if (Id != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (productId_ != null) {
        size += _single_productId_codec.CalculateSizeWithTag(ProductId);
      }
      if (MoneyAmount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MoneyAmount);
      }
      if (FreeAmount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FreeAmount);
      }
      if (price_ != null) {
        size += _single_price_codec.CalculateSizeWithTag(Price);
      }
      if (currency_ != null) {
        size += _single_currency_codec.CalculateSizeWithTag(Currency);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StoreProduct other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.productId_ != null) {
        if (productId_ == null || other.ProductId != "") {
          ProductId = other.ProductId;
        }
      }
      if (other.MoneyAmount != 0) {
        MoneyAmount = other.MoneyAmount;
      }
      if (other.FreeAmount != 0) {
        FreeAmount = other.FreeAmount;
      }
      if (other.price_ != null) {
        if (price_ == null || other.Price != 0D) {
          Price = other.Price;
        }
      }
      if (other.currency_ != null) {
        if (currency_ == null || other.Currency != "") {
          Currency = other.Currency;
        }
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            string value = _single_productId_codec.Read(input);
            if (productId_ == null || value != "") {
              ProductId = value;
            }
            break;
          }
          case 16: {
            MoneyAmount = input.ReadInt32();
            break;
          }
          case 24: {
            FreeAmount = input.ReadInt32();
            break;
          }
          case 34: {
            double? value = _single_price_codec.Read(input);
            if (price_ == null || value != 0D) {
              Price = value;
            }
            break;
          }
          case 42: {
            string value = _single_currency_codec.Read(input);
            if (currency_ == null || value != "") {
              Currency = value;
            }
            break;
          }
          case 48: {
            Id = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            string value = _single_productId_codec.Read(ref input);
            if (productId_ == null || value != "") {
              ProductId = value;
            }
            break;
          }
          case 16: {
            MoneyAmount = input.ReadInt32();
            break;
          }
          case 24: {
            FreeAmount = input.ReadInt32();
            break;
          }
          case 34: {
            double? value = _single_price_codec.Read(ref input);
            if (price_ == null || value != 0D) {
              Price = value;
            }
            break;
          }
          case 42: {
            string value = _single_currency_codec.Read(ref input);
            if (currency_ == null || value != "") {
              Currency = value;
            }
            break;
          }
          case 48: {
            Id = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
