// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: model/tension_card.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Neon.Model.Api.Model {

  /// <summary>Holder for reflection information generated from model/tension_card.proto</summary>
  public static partial class TensionCardReflection {

    #region Descriptor
    /// <summary>File descriptor for model/tension_card.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TensionCardReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chhtb2RlbC90ZW5zaW9uX2NhcmQucHJvdG8SCm5lb24ubW9kZWwaGGV4dGVu",
            "c2lvbi9lbGl4aXJwYi5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFt",
            "cC5wcm90bxocbW9kZWwvYWJpbGl0eV9lZmZpY2FjeS5wcm90byKPAgoLVGVu",
            "c2lvbkNhcmQSFwoPdGVuc2lvbl9jYXJkX2lkGAEgASgFEhEKCWVudGl0eV9p",
            "ZBgIIAEoBRILCgNleHAYAiABKAUSEwoLbGltaXRfYnJlYWsYAyABKAUSLwoL",
            "cmVjZWl2ZWRfYXQYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1w",
            "EhEKCW1heF9sZXZlbBgFIAEoBRI3ChJhYmlsaXR5X2VmZmljYWNpZXMYBiAD",
            "KAsyGy5uZW9uLm1vZGVsLkFiaWxpdHlFZmZpY2FjeRIiChp0cmFpbmluZ19z",
            "Y29yZV9sZXZlbF9zY29yZRgHIAEoBRIRCglpc19sb2NrZWQYCSABKAhCKaoC",
            "FE5lb24uTW9kZWwuQXBpLk1vZGVsukEPCg1OZW9uLlBCLk1vZGVsYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ApiClient.Extension.ElixirpbReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Neon.Model.Api.Model.AbilityEfficacyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Model.TensionCard), global::Neon.Model.Api.Model.TensionCard.Parser, new[]{ "TensionCardId", "EntityId", "Exp", "LimitBreak", "ReceivedAt", "MaxLevel", "AbilityEfficacies", "TrainingScoreLevelScore", "IsLocked" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TensionCard : pb::IMessage<TensionCard>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TensionCard> _parser = new pb::MessageParser<TensionCard>(() => new TensionCard());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TensionCard> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Model.TensionCardReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TensionCard() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TensionCard(TensionCard other) : this() {
      tensionCardId_ = other.tensionCardId_;
      entityId_ = other.entityId_;
      exp_ = other.exp_;
      limitBreak_ = other.limitBreak_;
      receivedAt_ = other.receivedAt_ != null ? other.receivedAt_.Clone() : null;
      maxLevel_ = other.maxLevel_;
      abilityEfficacies_ = other.abilityEfficacies_.Clone();
      trainingScoreLevelScore_ = other.trainingScoreLevelScore_;
      isLocked_ = other.isLocked_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TensionCard Clone() {
      return new TensionCard(this);
    }

    /// <summary>Field number for the "tension_card_id" field.</summary>
    public const int TensionCardIdFieldNumber = 1;
    private int tensionCardId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TensionCardId {
      get { return tensionCardId_; }
      set {
        tensionCardId_ = value;
      }
    }

    /// <summary>Field number for the "entity_id" field.</summary>
    public const int EntityIdFieldNumber = 8;
    private int entityId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EntityId {
      get { return entityId_; }
      set {
        entityId_ = value;
      }
    }

    /// <summary>Field number for the "exp" field.</summary>
    public const int ExpFieldNumber = 2;
    private int exp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Exp {
      get { return exp_; }
      set {
        exp_ = value;
      }
    }

    /// <summary>Field number for the "limit_break" field.</summary>
    public const int LimitBreakFieldNumber = 3;
    private int limitBreak_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LimitBreak {
      get { return limitBreak_; }
      set {
        limitBreak_ = value;
      }
    }

    /// <summary>Field number for the "received_at" field.</summary>
    public const int ReceivedAtFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Timestamp receivedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp ReceivedAt {
      get { return receivedAt_; }
      set {
        receivedAt_ = value;
      }
    }

    /// <summary>Field number for the "max_level" field.</summary>
    public const int MaxLevelFieldNumber = 5;
    private int maxLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxLevel {
      get { return maxLevel_; }
      set {
        maxLevel_ = value;
      }
    }

    /// <summary>Field number for the "ability_efficacies" field.</summary>
    public const int AbilityEfficaciesFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Neon.Model.Api.Model.AbilityEfficacy> _repeated_abilityEfficacies_codec
        = pb::FieldCodec.ForMessage(50, global::Neon.Model.Api.Model.AbilityEfficacy.Parser);
    private readonly pbc::RepeatedField<global::Neon.Model.Api.Model.AbilityEfficacy> abilityEfficacies_ = new pbc::RepeatedField<global::Neon.Model.Api.Model.AbilityEfficacy>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Neon.Model.Api.Model.AbilityEfficacy> AbilityEfficacies {
      get { return abilityEfficacies_; }
    }

    /// <summary>Field number for the "training_score_level_score" field.</summary>
    public const int TrainingScoreLevelScoreFieldNumber = 7;
    private int trainingScoreLevelScore_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TrainingScoreLevelScore {
      get { return trainingScoreLevelScore_; }
      set {
        trainingScoreLevelScore_ = value;
      }
    }

    /// <summary>Field number for the "is_locked" field.</summary>
    public const int IsLockedFieldNumber = 9;
    private bool isLocked_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsLocked {
      get { return isLocked_; }
      set {
        isLocked_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TensionCard);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TensionCard other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TensionCardId != other.TensionCardId) return false;
      if (EntityId != other.EntityId) return false;
      if (Exp != other.Exp) return false;
      if (LimitBreak != other.LimitBreak) return false;
      if (!object.Equals(ReceivedAt, other.ReceivedAt)) return false;
      if (MaxLevel != other.MaxLevel) return false;
      if(!abilityEfficacies_.Equals(other.abilityEfficacies_)) return false;
      if (TrainingScoreLevelScore != other.TrainingScoreLevelScore) return false;
      if (IsLocked != other.IsLocked) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TensionCardId != 0) hash ^= TensionCardId.GetHashCode();
      if (EntityId != 0) hash ^= EntityId.GetHashCode();
      if (Exp != 0) hash ^= Exp.GetHashCode();
      if (LimitBreak != 0) hash ^= LimitBreak.GetHashCode();
      if (receivedAt_ != null) hash ^= ReceivedAt.GetHashCode();
      if (MaxLevel != 0) hash ^= MaxLevel.GetHashCode();
      hash ^= abilityEfficacies_.GetHashCode();
      if (TrainingScoreLevelScore != 0) hash ^= TrainingScoreLevelScore.GetHashCode();
      if (IsLocked != false) hash ^= IsLocked.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TensionCardId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TensionCardId);
      }
      if (Exp != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Exp);
      }
      if (LimitBreak != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(LimitBreak);
      }
      if (receivedAt_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ReceivedAt);
      }
      if (MaxLevel != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(MaxLevel);
      }
      abilityEfficacies_.WriteTo(output, _repeated_abilityEfficacies_codec);
      if (TrainingScoreLevelScore != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(TrainingScoreLevelScore);
      }
      if (EntityId != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(EntityId);
      }
      if (IsLocked != false) {
        output.WriteRawTag(72);
        output.WriteBool(IsLocked);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TensionCardId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TensionCardId);
      }
      if (Exp != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Exp);
      }
      if (LimitBreak != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(LimitBreak);
      }
      if (receivedAt_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ReceivedAt);
      }
      if (MaxLevel != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(MaxLevel);
      }
      abilityEfficacies_.WriteTo(ref output, _repeated_abilityEfficacies_codec);
      if (TrainingScoreLevelScore != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(TrainingScoreLevelScore);
      }
      if (EntityId != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(EntityId);
      }
      if (IsLocked != false) {
        output.WriteRawTag(72);
        output.WriteBool(IsLocked);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TensionCardId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TensionCardId);
      }
      if (EntityId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EntityId);
      }
      if (Exp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Exp);
      }
      if (LimitBreak != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LimitBreak);
      }
      if (receivedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ReceivedAt);
      }
      if (MaxLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxLevel);
      }
      size += abilityEfficacies_.CalculateSize(_repeated_abilityEfficacies_codec);
      if (TrainingScoreLevelScore != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TrainingScoreLevelScore);
      }
      if (IsLocked != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TensionCard other) {
      if (other == null) {
        return;
      }
      if (other.TensionCardId != 0) {
        TensionCardId = other.TensionCardId;
      }
      if (other.EntityId != 0) {
        EntityId = other.EntityId;
      }
      if (other.Exp != 0) {
        Exp = other.Exp;
      }
      if (other.LimitBreak != 0) {
        LimitBreak = other.LimitBreak;
      }
      if (other.receivedAt_ != null) {
        if (receivedAt_ == null) {
          ReceivedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        ReceivedAt.MergeFrom(other.ReceivedAt);
      }
      if (other.MaxLevel != 0) {
        MaxLevel = other.MaxLevel;
      }
      abilityEfficacies_.Add(other.abilityEfficacies_);
      if (other.TrainingScoreLevelScore != 0) {
        TrainingScoreLevelScore = other.TrainingScoreLevelScore;
      }
      if (other.IsLocked != false) {
        IsLocked = other.IsLocked;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TensionCardId = input.ReadInt32();
            break;
          }
          case 16: {
            Exp = input.ReadInt32();
            break;
          }
          case 24: {
            LimitBreak = input.ReadInt32();
            break;
          }
          case 34: {
            if (receivedAt_ == null) {
              ReceivedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ReceivedAt);
            break;
          }
          case 40: {
            MaxLevel = input.ReadInt32();
            break;
          }
          case 50: {
            abilityEfficacies_.AddEntriesFrom(input, _repeated_abilityEfficacies_codec);
            break;
          }
          case 56: {
            TrainingScoreLevelScore = input.ReadInt32();
            break;
          }
          case 64: {
            EntityId = input.ReadInt32();
            break;
          }
          case 72: {
            IsLocked = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TensionCardId = input.ReadInt32();
            break;
          }
          case 16: {
            Exp = input.ReadInt32();
            break;
          }
          case 24: {
            LimitBreak = input.ReadInt32();
            break;
          }
          case 34: {
            if (receivedAt_ == null) {
              ReceivedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ReceivedAt);
            break;
          }
          case 40: {
            MaxLevel = input.ReadInt32();
            break;
          }
          case 50: {
            abilityEfficacies_.AddEntriesFrom(ref input, _repeated_abilityEfficacies_codec);
            break;
          }
          case 56: {
            TrainingScoreLevelScore = input.ReadInt32();
            break;
          }
          case 64: {
            EntityId = input.ReadInt32();
            break;
          }
          case 72: {
            IsLocked = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
