// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api/event.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Neon.Model.Api.Rpc {

  /// <summary>Holder for reflection information generated from api/event.proto</summary>
  public static partial class EventReflection {

    #region Descriptor
    /// <summary>File descriptor for api/event.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EventReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9hcGkvZXZlbnQucHJvdG8SCG5lb24uYXBpGhtnb29nbGUvcHJvdG9idWYv",
            "ZW1wdHkucHJvdG8aGGV4dGVuc2lvbi9lbGl4aXJwYi5wcm90bxoVZXh0ZW5z",
            "aW9uL2FwaXBiLnByb3RvGhhleHRlbnNpb24vdmFsaWRhdGUucHJvdG8aG2Fw",
            "aS9jaGFuZ2VkX3Jlc291cmNlcy5wcm90bxoXZW51bS9xdWVzdF9yZXN1bHQu",
            "cHJvdG8aHG1vZGVsL2V2ZW50X2Zsb29yX25vZGUucHJvdG8aFW1vZGVsL3Jl",
            "c291cmNlcy5wcm90bxoSbW9kZWwvcmV3YXJkLnByb3RvIt4BChZFdmVudEZp",
            "bmlzaE5vZGVSZXF1ZXN0EhsKE2V2ZW50X2Zsb29yX25vZGVfaWQYASABKAUS",
            "KQoXY2xlYXJlZF9hY2hpZXZlbWVudF9pZHMYAyADKAVCCPpCBZIBAhgBEhcK",
            "D2lzX2NvbnN1bWVfaXRlbRgEIAEoCBI1CgZyZXN1bHQYBSABKAsyJS5uZW9u",
            "Lm1vZGVsLkV2ZW50Rmxvb3JOb2RlUXVlc3RSZXN1bHQSLAoMcXVlc3RfcmVz",
            "dWx0GAYgASgOMhYubmVvbi5lbnVtLlF1ZXN0UmVzdWx0InAKF0V2ZW50Rmlu",
            "aXNoTm9kZVJlc3BvbnNlEiMKB3Jld2FyZHMYASADKAsyEi5uZW9uLm1vZGVs",
            "LlJld2FyZBIwChFjaGFuZ2VkX3Jlc291cmNlcxgCIAEoCzIVLm5lb24ubW9k",
            "ZWwuUmVzb3VyY2VzMtICCgVFdmVudBKNAQoITGlzdE5vZGUSFi5nb29nbGUu",
            "cHJvdG9idWYuRW1wdHkaIi5uZW9uLmFwaS5DaGFuZ2VkUmVzb3VyY2VzUmVz",
            "cG9uc2UiRYK1GEEKEC9ldmVudC9saXN0X25vZGUSLeino+aUvuOBleOCjOOB",
            "puOBhOOCi+ODjuODvOODieOCkuWPluW+l+OBmeOCixK4AQoKRmluaXNoTm9k",
            "ZRIgLm5lb24uYXBpLkV2ZW50RmluaXNoTm9kZVJlcXVlc3QaIS5uZW9uLmFw",
            "aS5FdmVudEZpbmlzaE5vZGVSZXNwb25zZSJlgrUYYQoSL2V2ZW50L2Zpbmlz",
            "aF9ub2RlEifjgqTjg5njg7Pjg4jjg47jg7zjg4njgpLjgq/jg6rjgqLjgZnj",
            "gosiD291dF9vZl9zY2hlZHVsZSIRcmV3YXJkX292ZXJmbG93ZWRCKJABAaoC",
            "Ek5lb24uTW9kZWwuQXBpLlJwY7pBDQoLTmVvbi5QQi5BUEliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::ApiClient.Extension.ElixirpbReflection.Descriptor, global::ApiClient.Extension.ApipbReflection.Descriptor, global::ApiClient.Extension.ValidateReflection.Descriptor, global::Neon.Model.Api.Rpc.ChangedResourcesReflection.Descriptor, global::Neon.Model.Api.Enum.QuestResultReflection.Descriptor, global::Neon.Model.Api.Model.EventFloorNodeReflection.Descriptor, global::Neon.Model.Api.Model.ResourcesReflection.Descriptor, global::Neon.Model.Api.Model.RewardReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.EventFinishNodeRequest), global::Neon.Model.Api.Rpc.EventFinishNodeRequest.Parser, new[]{ "EventFloorNodeId", "ClearedAchievementIds", "IsConsumeItem", "Result", "QuestResult" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.EventFinishNodeResponse), global::Neon.Model.Api.Rpc.EventFinishNodeResponse.Parser, new[]{ "Rewards", "ChangedResources" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EventFinishNodeRequest : pb::IMessage<EventFinishNodeRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EventFinishNodeRequest> _parser = new pb::MessageParser<EventFinishNodeRequest>(() => new EventFinishNodeRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EventFinishNodeRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.EventReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventFinishNodeRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventFinishNodeRequest(EventFinishNodeRequest other) : this() {
      eventFloorNodeId_ = other.eventFloorNodeId_;
      clearedAchievementIds_ = other.clearedAchievementIds_.Clone();
      isConsumeItem_ = other.isConsumeItem_;
      result_ = other.result_ != null ? other.result_.Clone() : null;
      questResult_ = other.questResult_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventFinishNodeRequest Clone() {
      return new EventFinishNodeRequest(this);
    }

    /// <summary>Field number for the "event_floor_node_id" field.</summary>
    public const int EventFloorNodeIdFieldNumber = 1;
    private int eventFloorNodeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EventFloorNodeId {
      get { return eventFloorNodeId_; }
      set {
        eventFloorNodeId_ = value;
      }
    }

    /// <summary>Field number for the "cleared_achievement_ids" field.</summary>
    public const int ClearedAchievementIdsFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_clearedAchievementIds_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> clearedAchievementIds_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> ClearedAchievementIds {
      get { return clearedAchievementIds_; }
    }

    /// <summary>Field number for the "is_consume_item" field.</summary>
    public const int IsConsumeItemFieldNumber = 4;
    private bool isConsumeItem_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsConsumeItem {
      get { return isConsumeItem_; }
      set {
        isConsumeItem_ = value;
      }
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 5;
    private global::Neon.Model.Api.Model.EventFloorNodeQuestResult result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Model.Api.Model.EventFloorNodeQuestResult Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "quest_result" field.</summary>
    public const int QuestResultFieldNumber = 6;
    private global::Neon.Model.Api.Enum.QuestResult questResult_ = global::Neon.Model.Api.Enum.QuestResult.Cleared;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Model.Api.Enum.QuestResult QuestResult {
      get { return questResult_; }
      set {
        questResult_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EventFinishNodeRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EventFinishNodeRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EventFloorNodeId != other.EventFloorNodeId) return false;
      if(!clearedAchievementIds_.Equals(other.clearedAchievementIds_)) return false;
      if (IsConsumeItem != other.IsConsumeItem) return false;
      if (!object.Equals(Result, other.Result)) return false;
      if (QuestResult != other.QuestResult) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EventFloorNodeId != 0) hash ^= EventFloorNodeId.GetHashCode();
      hash ^= clearedAchievementIds_.GetHashCode();
      if (IsConsumeItem != false) hash ^= IsConsumeItem.GetHashCode();
      if (result_ != null) hash ^= Result.GetHashCode();
      if (QuestResult != global::Neon.Model.Api.Enum.QuestResult.Cleared) hash ^= QuestResult.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EventFloorNodeId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EventFloorNodeId);
      }
      clearedAchievementIds_.WriteTo(output, _repeated_clearedAchievementIds_codec);
      if (IsConsumeItem != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsConsumeItem);
      }
      if (result_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Result);
      }
      if (QuestResult != global::Neon.Model.Api.Enum.QuestResult.Cleared) {
        output.WriteRawTag(48);
        output.WriteEnum((int) QuestResult);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EventFloorNodeId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EventFloorNodeId);
      }
      clearedAchievementIds_.WriteTo(ref output, _repeated_clearedAchievementIds_codec);
      if (IsConsumeItem != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsConsumeItem);
      }
      if (result_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Result);
      }
      if (QuestResult != global::Neon.Model.Api.Enum.QuestResult.Cleared) {
        output.WriteRawTag(48);
        output.WriteEnum((int) QuestResult);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EventFloorNodeId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EventFloorNodeId);
      }
      size += clearedAchievementIds_.CalculateSize(_repeated_clearedAchievementIds_codec);
      if (IsConsumeItem != false) {
        size += 1 + 1;
      }
      if (result_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
      }
      if (QuestResult != global::Neon.Model.Api.Enum.QuestResult.Cleared) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) QuestResult);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EventFinishNodeRequest other) {
      if (other == null) {
        return;
      }
      if (other.EventFloorNodeId != 0) {
        EventFloorNodeId = other.EventFloorNodeId;
      }
      clearedAchievementIds_.Add(other.clearedAchievementIds_);
      if (other.IsConsumeItem != false) {
        IsConsumeItem = other.IsConsumeItem;
      }
      if (other.result_ != null) {
        if (result_ == null) {
          Result = new global::Neon.Model.Api.Model.EventFloorNodeQuestResult();
        }
        Result.MergeFrom(other.Result);
      }
      if (other.QuestResult != global::Neon.Model.Api.Enum.QuestResult.Cleared) {
        QuestResult = other.QuestResult;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EventFloorNodeId = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            clearedAchievementIds_.AddEntriesFrom(input, _repeated_clearedAchievementIds_codec);
            break;
          }
          case 32: {
            IsConsumeItem = input.ReadBool();
            break;
          }
          case 42: {
            if (result_ == null) {
              Result = new global::Neon.Model.Api.Model.EventFloorNodeQuestResult();
            }
            input.ReadMessage(Result);
            break;
          }
          case 48: {
            QuestResult = (global::Neon.Model.Api.Enum.QuestResult) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EventFloorNodeId = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            clearedAchievementIds_.AddEntriesFrom(ref input, _repeated_clearedAchievementIds_codec);
            break;
          }
          case 32: {
            IsConsumeItem = input.ReadBool();
            break;
          }
          case 42: {
            if (result_ == null) {
              Result = new global::Neon.Model.Api.Model.EventFloorNodeQuestResult();
            }
            input.ReadMessage(Result);
            break;
          }
          case 48: {
            QuestResult = (global::Neon.Model.Api.Enum.QuestResult) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EventFinishNodeResponse : pb::IMessage<EventFinishNodeResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EventFinishNodeResponse> _parser = new pb::MessageParser<EventFinishNodeResponse>(() => new EventFinishNodeResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EventFinishNodeResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.EventReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventFinishNodeResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventFinishNodeResponse(EventFinishNodeResponse other) : this() {
      rewards_ = other.rewards_.Clone();
      changedResources_ = other.changedResources_ != null ? other.changedResources_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EventFinishNodeResponse Clone() {
      return new EventFinishNodeResponse(this);
    }

    /// <summary>Field number for the "rewards" field.</summary>
    public const int RewardsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Neon.Model.Api.Model.Reward> _repeated_rewards_codec
        = pb::FieldCodec.ForMessage(10, global::Neon.Model.Api.Model.Reward.Parser);
    private readonly pbc::RepeatedField<global::Neon.Model.Api.Model.Reward> rewards_ = new pbc::RepeatedField<global::Neon.Model.Api.Model.Reward>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Neon.Model.Api.Model.Reward> Rewards {
      get { return rewards_; }
    }

    /// <summary>Field number for the "changed_resources" field.</summary>
    public const int ChangedResourcesFieldNumber = 2;
    private global::Neon.Model.Api.Model.Resources changedResources_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Model.Api.Model.Resources ChangedResources {
      get { return changedResources_; }
      set {
        changedResources_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EventFinishNodeResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EventFinishNodeResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!rewards_.Equals(other.rewards_)) return false;
      if (!object.Equals(ChangedResources, other.ChangedResources)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= rewards_.GetHashCode();
      if (changedResources_ != null) hash ^= ChangedResources.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      rewards_.WriteTo(output, _repeated_rewards_codec);
      if (changedResources_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangedResources);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      rewards_.WriteTo(ref output, _repeated_rewards_codec);
      if (changedResources_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangedResources);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += rewards_.CalculateSize(_repeated_rewards_codec);
      if (changedResources_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChangedResources);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EventFinishNodeResponse other) {
      if (other == null) {
        return;
      }
      rewards_.Add(other.rewards_);
      if (other.changedResources_ != null) {
        if (changedResources_ == null) {
          ChangedResources = new global::Neon.Model.Api.Model.Resources();
        }
        ChangedResources.MergeFrom(other.ChangedResources);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            rewards_.AddEntriesFrom(input, _repeated_rewards_codec);
            break;
          }
          case 18: {
            if (changedResources_ == null) {
              ChangedResources = new global::Neon.Model.Api.Model.Resources();
            }
            input.ReadMessage(ChangedResources);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            rewards_.AddEntriesFrom(ref input, _repeated_rewards_codec);
            break;
          }
          case 18: {
            if (changedResources_ == null) {
              ChangedResources = new global::Neon.Model.Api.Model.Resources();
            }
            input.ReadMessage(ChangedResources);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
