// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api/happy_worker.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Neon.Model.Api.Rpc {

  /// <summary>Holder for reflection information generated from api/happy_worker.proto</summary>
  public static partial class HappyWorkerReflection {

    #region Descriptor
    /// <summary>File descriptor for api/happy_worker.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HappyWorkerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZhcGkvaGFwcHlfd29ya2VyLnByb3RvEghuZW9uLmFwaRoYZXh0ZW5zaW9u",
            "L2VsaXhpcnBiLnByb3RvGhVleHRlbnNpb24vYXBpcGIucHJvdG8aGGV4dGVu",
            "c2lvbi92YWxpZGF0ZS5wcm90bxocbW9kZWwvY3VycmVudF9sb2NhdGlvbi5w",
            "cm90bxodbW9kZWwvaGFwcHlfd29ya2VyX2l0ZW0ucHJvdG8aFW1vZGVsL3Jl",
            "c291cmNlcy5wcm90byJZChZIYXBweVdvcmtlckxpc3RSZXF1ZXN0Ej8KEGN1",
            "cnJlbnRfbG9jYXRpb24YASABKAsyGy5uZW9uLm1vZGVsLkN1cnJlbnRMb2Nh",
            "dGlvbkII+kIFigECEAEihAEKF0hhcHB5V29ya2VyTGlzdFJlc3BvbnNlEjcK",
            "EmhhcHB5X3dvcmtlcl9pdGVtcxgBIAMoCzIbLm5lb24ubW9kZWwuSGFwcHlX",
            "b3JrZXJJdGVtEjAKEWNoYW5nZWRfcmVzb3VyY2VzGAIgASgLMhUubmVvbi5t",
            "b2RlbC5SZXNvdXJjZXMiNwoXSGFwcHlXb3JrZXJTdGFydFJlcXVlc3QSHAoU",
            "aGFwcHlfd29ya2VyX2l0ZW1faWQYASABKAUihAEKGEhhcHB5V29ya2VyU3Rh",
            "cnRSZXNwb25zZRI2ChFoYXBweV93b3JrZXJfaXRlbRgBIAEoCzIbLm5lb24u",
            "bW9kZWwuSGFwcHlXb3JrZXJJdGVtEjAKEWNoYW5nZWRfcmVzb3VyY2VzGAIg",
            "ASgLMhUubmVvbi5tb2RlbC5SZXNvdXJjZXMiOAoYSGFwcHlXb3JrZXJDYW5j",
            "ZWxSZXF1ZXN0EhwKFGhhcHB5X3dvcmtlcl9pdGVtX2lkGAEgASgFIoUBChlI",
            "YXBweVdvcmtlckNhbmNlbFJlc3BvbnNlEjYKEWhhcHB5X3dvcmtlcl9pdGVt",
            "GAEgASgLMhsubmVvbi5tb2RlbC5IYXBweVdvcmtlckl0ZW0SMAoRY2hhbmdl",
            "ZF9yZXNvdXJjZXMYAiABKAsyFS5uZW9uLm1vZGVsLlJlc291cmNlczKeBgoL",
            "SGFwcHlXb3JrZXIS/QEKBExpc3QSIC5uZW9uLmFwaS5IYXBweVdvcmtlckxp",
            "c3RSZXF1ZXN0GiEubmVvbi5hcGkuSGFwcHlXb3JrZXJMaXN0UmVzcG9uc2Ui",
            "rwGCtRiqAQoSL2hhcHB5X3dvcmtlci9saXN0EpMB44OP44OD44OU44O844Ov",
            "44O844Kr44O844Gr6KGo56S644GV44KM44KL44OB44Oj44Os44Oz44K477yI",
            "44OH44Kk44Oq44O844O744Gd44Gu5LuW77yJ5LiA6Kan44KS6L+U44GZ44CC",
            "5b+F6KaB44Gq44KJ44OH44Kk44Oq44O844KC5oq96YG444GZ44KL44CCEuMC",
            "CgVTdGFydBIhLm5lb24uYXBpLkhhcHB5V29ya2VyU3RhcnRSZXF1ZXN0GiIu",
            "bmVvbi5hcGkuSGFwcHlXb3JrZXJTdGFydFJlc3BvbnNlIpICgrUYjQIKEy9o",
            "YXBweV93b3JrZXIvc3RhcnQS4gHjg4/jg4Pjg5Tjg7zjg6/jg7zjgqvjg7zj",
            "gafjg4Hjg6Pjg6zjg7PjgrjjgpLlj5fms6jjgZnjgovjgILkuK3mlq3jgZfj",
            "gabjgYTjgZ/jg4Hjg6Pjg6zjg7PjgrjjgpLlho3plovjgZnjgovpmpvjgoLj",
            "gZPjgaHjgonjgpLliKnnlKjjgILlj5fms6jjg7vlho3plovmmYLjgavjgq/j",
            "g6rjgqLmmYLloLHphazjgYzmuqLjgozjgovloLTlkIjjga8gcmV3YXJkX292",
            "ZXJmbG93ZWQg44KS6L+U44GZ44CCIhFyZXdhcmRfb3ZlcmZsb3dlZBKoAQoG",
            "Q2FuY2VsEiIubmVvbi5hcGkuSGFwcHlXb3JrZXJDYW5jZWxSZXF1ZXN0GiMu",
            "bmVvbi5hcGkuSGFwcHlXb3JrZXJDYW5jZWxSZXNwb25zZSJVgrUYUQoUL2hh",
            "cHB5X3dvcmtlci9jYW5jZWwSOeODj+ODg+ODlOODvOODr+ODvOOCq+ODvOOB",
            "p+ODgeODo+ODrOODs+OCuOOCkuS4reatouOBmeOCi0IokAEBqgISTmVvbi5N",
            "b2RlbC5BcGkuUnBjukENCgtOZW9uLlBCLkFQSWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ApiClient.Extension.ElixirpbReflection.Descriptor, global::ApiClient.Extension.ApipbReflection.Descriptor, global::ApiClient.Extension.ValidateReflection.Descriptor, global::Neon.Model.Api.Model.CurrentLocationReflection.Descriptor, global::Neon.Model.Api.Model.HappyWorkerItemReflection.Descriptor, global::Neon.Model.Api.Model.ResourcesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.HappyWorkerListRequest), global::Neon.Model.Api.Rpc.HappyWorkerListRequest.Parser, new[]{ "CurrentLocation" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.HappyWorkerListResponse), global::Neon.Model.Api.Rpc.HappyWorkerListResponse.Parser, new[]{ "HappyWorkerItems", "ChangedResources" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.HappyWorkerStartRequest), global::Neon.Model.Api.Rpc.HappyWorkerStartRequest.Parser, new[]{ "HappyWorkerItemId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.HappyWorkerStartResponse), global::Neon.Model.Api.Rpc.HappyWorkerStartResponse.Parser, new[]{ "HappyWorkerItem", "ChangedResources" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.HappyWorkerCancelRequest), global::Neon.Model.Api.Rpc.HappyWorkerCancelRequest.Parser, new[]{ "HappyWorkerItemId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.HappyWorkerCancelResponse), global::Neon.Model.Api.Rpc.HappyWorkerCancelResponse.Parser, new[]{ "HappyWorkerItem", "ChangedResources" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HappyWorkerListRequest : pb::IMessage<HappyWorkerListRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HappyWorkerListRequest> _parser = new pb::MessageParser<HappyWorkerListRequest>(() => new HappyWorkerListRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HappyWorkerListRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.HappyWorkerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HappyWorkerListRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HappyWorkerListRequest(HappyWorkerListRequest other) : this() {
      currentLocation_ = other.currentLocation_ != null ? other.currentLocation_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HappyWorkerListRequest Clone() {
      return new HappyWorkerListRequest(this);
    }

    /// <summary>Field number for the "current_location" field.</summary>
    public const int CurrentLocationFieldNumber = 1;
    private global::Neon.Model.Api.Model.CurrentLocation currentLocation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Model.Api.Model.CurrentLocation CurrentLocation {
      get { return currentLocation_; }
      set {
        currentLocation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HappyWorkerListRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HappyWorkerListRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CurrentLocation, other.CurrentLocation)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (currentLocation_ != null) hash ^= CurrentLocation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (currentLocation_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CurrentLocation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (currentLocation_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CurrentLocation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (currentLocation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurrentLocation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HappyWorkerListRequest other) {
      if (other == null) {
        return;
      }
      if (other.currentLocation_ != null) {
        if (currentLocation_ == null) {
          CurrentLocation = new global::Neon.Model.Api.Model.CurrentLocation();
        }
        CurrentLocation.MergeFrom(other.CurrentLocation);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (currentLocation_ == null) {
              CurrentLocation = new global::Neon.Model.Api.Model.CurrentLocation();
            }
            input.ReadMessage(CurrentLocation);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (currentLocation_ == null) {
              CurrentLocation = new global::Neon.Model.Api.Model.CurrentLocation();
            }
            input.ReadMessage(CurrentLocation);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HappyWorkerListResponse : pb::IMessage<HappyWorkerListResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HappyWorkerListResponse> _parser = new pb::MessageParser<HappyWorkerListResponse>(() => new HappyWorkerListResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HappyWorkerListResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.HappyWorkerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HappyWorkerListResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HappyWorkerListResponse(HappyWorkerListResponse other) : this() {
      happyWorkerItems_ = other.happyWorkerItems_.Clone();
      changedResources_ = other.changedResources_ != null ? other.changedResources_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HappyWorkerListResponse Clone() {
      return new HappyWorkerListResponse(this);
    }

    /// <summary>Field number for the "happy_worker_items" field.</summary>
    public const int HappyWorkerItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Neon.Model.Api.Model.HappyWorkerItem> _repeated_happyWorkerItems_codec
        = pb::FieldCodec.ForMessage(10, global::Neon.Model.Api.Model.HappyWorkerItem.Parser);
    private readonly pbc::RepeatedField<global::Neon.Model.Api.Model.HappyWorkerItem> happyWorkerItems_ = new pbc::RepeatedField<global::Neon.Model.Api.Model.HappyWorkerItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Neon.Model.Api.Model.HappyWorkerItem> HappyWorkerItems {
      get { return happyWorkerItems_; }
    }

    /// <summary>Field number for the "changed_resources" field.</summary>
    public const int ChangedResourcesFieldNumber = 2;
    private global::Neon.Model.Api.Model.Resources changedResources_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Model.Api.Model.Resources ChangedResources {
      get { return changedResources_; }
      set {
        changedResources_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HappyWorkerListResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HappyWorkerListResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!happyWorkerItems_.Equals(other.happyWorkerItems_)) return false;
      if (!object.Equals(ChangedResources, other.ChangedResources)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= happyWorkerItems_.GetHashCode();
      if (changedResources_ != null) hash ^= ChangedResources.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      happyWorkerItems_.WriteTo(output, _repeated_happyWorkerItems_codec);
      if (changedResources_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangedResources);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      happyWorkerItems_.WriteTo(ref output, _repeated_happyWorkerItems_codec);
      if (changedResources_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangedResources);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += happyWorkerItems_.CalculateSize(_repeated_happyWorkerItems_codec);
      if (changedResources_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChangedResources);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HappyWorkerListResponse other) {
      if (other == null) {
        return;
      }
      happyWorkerItems_.Add(other.happyWorkerItems_);
      if (other.changedResources_ != null) {
        if (changedResources_ == null) {
          ChangedResources = new global::Neon.Model.Api.Model.Resources();
        }
        ChangedResources.MergeFrom(other.ChangedResources);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            happyWorkerItems_.AddEntriesFrom(input, _repeated_happyWorkerItems_codec);
            break;
          }
          case 18: {
            if (changedResources_ == null) {
              ChangedResources = new global::Neon.Model.Api.Model.Resources();
            }
            input.ReadMessage(ChangedResources);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            happyWorkerItems_.AddEntriesFrom(ref input, _repeated_happyWorkerItems_codec);
            break;
          }
          case 18: {
            if (changedResources_ == null) {
              ChangedResources = new global::Neon.Model.Api.Model.Resources();
            }
            input.ReadMessage(ChangedResources);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HappyWorkerStartRequest : pb::IMessage<HappyWorkerStartRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HappyWorkerStartRequest> _parser = new pb::MessageParser<HappyWorkerStartRequest>(() => new HappyWorkerStartRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HappyWorkerStartRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.HappyWorkerReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HappyWorkerStartRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HappyWorkerStartRequest(HappyWorkerStartRequest other) : this() {
      happyWorkerItemId_ = other.happyWorkerItemId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HappyWorkerStartRequest Clone() {
      return new HappyWorkerStartRequest(this);
    }

    /// <summary>Field number for the "happy_worker_item_id" field.</summary>
    public const int HappyWorkerItemIdFieldNumber = 1;
    private int happyWorkerItemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int HappyWorkerItemId {
      get { return happyWorkerItemId_; }
      set {
        happyWorkerItemId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HappyWorkerStartRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HappyWorkerStartRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (HappyWorkerItemId != other.HappyWorkerItemId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HappyWorkerItemId != 0) hash ^= HappyWorkerItemId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HappyWorkerItemId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(HappyWorkerItemId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HappyWorkerItemId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(HappyWorkerItemId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HappyWorkerItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HappyWorkerItemId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HappyWorkerStartRequest other) {
      if (other == null) {
        return;
      }
      if (other.HappyWorkerItemId != 0) {
        HappyWorkerItemId = other.HappyWorkerItemId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            HappyWorkerItemId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            HappyWorkerItemId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HappyWorkerStartResponse : pb::IMessage<HappyWorkerStartResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HappyWorkerStartResponse> _parser = new pb::MessageParser<HappyWorkerStartResponse>(() => new HappyWorkerStartResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HappyWorkerStartResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.HappyWorkerReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HappyWorkerStartResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HappyWorkerStartResponse(HappyWorkerStartResponse other) : this() {
      happyWorkerItem_ = other.happyWorkerItem_ != null ? other.happyWorkerItem_.Clone() : null;
      changedResources_ = other.changedResources_ != null ? other.changedResources_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HappyWorkerStartResponse Clone() {
      return new HappyWorkerStartResponse(this);
    }

    /// <summary>Field number for the "happy_worker_item" field.</summary>
    public const int HappyWorkerItemFieldNumber = 1;
    private global::Neon.Model.Api.Model.HappyWorkerItem happyWorkerItem_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Model.Api.Model.HappyWorkerItem HappyWorkerItem {
      get { return happyWorkerItem_; }
      set {
        happyWorkerItem_ = value;
      }
    }

    /// <summary>Field number for the "changed_resources" field.</summary>
    public const int ChangedResourcesFieldNumber = 2;
    private global::Neon.Model.Api.Model.Resources changedResources_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Model.Api.Model.Resources ChangedResources {
      get { return changedResources_; }
      set {
        changedResources_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HappyWorkerStartResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HappyWorkerStartResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(HappyWorkerItem, other.HappyWorkerItem)) return false;
      if (!object.Equals(ChangedResources, other.ChangedResources)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (happyWorkerItem_ != null) hash ^= HappyWorkerItem.GetHashCode();
      if (changedResources_ != null) hash ^= ChangedResources.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (happyWorkerItem_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(HappyWorkerItem);
      }
      if (changedResources_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangedResources);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (happyWorkerItem_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(HappyWorkerItem);
      }
      if (changedResources_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangedResources);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (happyWorkerItem_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HappyWorkerItem);
      }
      if (changedResources_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChangedResources);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HappyWorkerStartResponse other) {
      if (other == null) {
        return;
      }
      if (other.happyWorkerItem_ != null) {
        if (happyWorkerItem_ == null) {
          HappyWorkerItem = new global::Neon.Model.Api.Model.HappyWorkerItem();
        }
        HappyWorkerItem.MergeFrom(other.HappyWorkerItem);
      }
      if (other.changedResources_ != null) {
        if (changedResources_ == null) {
          ChangedResources = new global::Neon.Model.Api.Model.Resources();
        }
        ChangedResources.MergeFrom(other.ChangedResources);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (happyWorkerItem_ == null) {
              HappyWorkerItem = new global::Neon.Model.Api.Model.HappyWorkerItem();
            }
            input.ReadMessage(HappyWorkerItem);
            break;
          }
          case 18: {
            if (changedResources_ == null) {
              ChangedResources = new global::Neon.Model.Api.Model.Resources();
            }
            input.ReadMessage(ChangedResources);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (happyWorkerItem_ == null) {
              HappyWorkerItem = new global::Neon.Model.Api.Model.HappyWorkerItem();
            }
            input.ReadMessage(HappyWorkerItem);
            break;
          }
          case 18: {
            if (changedResources_ == null) {
              ChangedResources = new global::Neon.Model.Api.Model.Resources();
            }
            input.ReadMessage(ChangedResources);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HappyWorkerCancelRequest : pb::IMessage<HappyWorkerCancelRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HappyWorkerCancelRequest> _parser = new pb::MessageParser<HappyWorkerCancelRequest>(() => new HappyWorkerCancelRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HappyWorkerCancelRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.HappyWorkerReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HappyWorkerCancelRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HappyWorkerCancelRequest(HappyWorkerCancelRequest other) : this() {
      happyWorkerItemId_ = other.happyWorkerItemId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HappyWorkerCancelRequest Clone() {
      return new HappyWorkerCancelRequest(this);
    }

    /// <summary>Field number for the "happy_worker_item_id" field.</summary>
    public const int HappyWorkerItemIdFieldNumber = 1;
    private int happyWorkerItemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int HappyWorkerItemId {
      get { return happyWorkerItemId_; }
      set {
        happyWorkerItemId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HappyWorkerCancelRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HappyWorkerCancelRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (HappyWorkerItemId != other.HappyWorkerItemId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HappyWorkerItemId != 0) hash ^= HappyWorkerItemId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HappyWorkerItemId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(HappyWorkerItemId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HappyWorkerItemId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(HappyWorkerItemId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HappyWorkerItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HappyWorkerItemId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HappyWorkerCancelRequest other) {
      if (other == null) {
        return;
      }
      if (other.HappyWorkerItemId != 0) {
        HappyWorkerItemId = other.HappyWorkerItemId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            HappyWorkerItemId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            HappyWorkerItemId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HappyWorkerCancelResponse : pb::IMessage<HappyWorkerCancelResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HappyWorkerCancelResponse> _parser = new pb::MessageParser<HappyWorkerCancelResponse>(() => new HappyWorkerCancelResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HappyWorkerCancelResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.HappyWorkerReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HappyWorkerCancelResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HappyWorkerCancelResponse(HappyWorkerCancelResponse other) : this() {
      happyWorkerItem_ = other.happyWorkerItem_ != null ? other.happyWorkerItem_.Clone() : null;
      changedResources_ = other.changedResources_ != null ? other.changedResources_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HappyWorkerCancelResponse Clone() {
      return new HappyWorkerCancelResponse(this);
    }

    /// <summary>Field number for the "happy_worker_item" field.</summary>
    public const int HappyWorkerItemFieldNumber = 1;
    private global::Neon.Model.Api.Model.HappyWorkerItem happyWorkerItem_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Model.Api.Model.HappyWorkerItem HappyWorkerItem {
      get { return happyWorkerItem_; }
      set {
        happyWorkerItem_ = value;
      }
    }

    /// <summary>Field number for the "changed_resources" field.</summary>
    public const int ChangedResourcesFieldNumber = 2;
    private global::Neon.Model.Api.Model.Resources changedResources_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Model.Api.Model.Resources ChangedResources {
      get { return changedResources_; }
      set {
        changedResources_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HappyWorkerCancelResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HappyWorkerCancelResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(HappyWorkerItem, other.HappyWorkerItem)) return false;
      if (!object.Equals(ChangedResources, other.ChangedResources)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (happyWorkerItem_ != null) hash ^= HappyWorkerItem.GetHashCode();
      if (changedResources_ != null) hash ^= ChangedResources.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (happyWorkerItem_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(HappyWorkerItem);
      }
      if (changedResources_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangedResources);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (happyWorkerItem_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(HappyWorkerItem);
      }
      if (changedResources_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangedResources);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (happyWorkerItem_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HappyWorkerItem);
      }
      if (changedResources_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChangedResources);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HappyWorkerCancelResponse other) {
      if (other == null) {
        return;
      }
      if (other.happyWorkerItem_ != null) {
        if (happyWorkerItem_ == null) {
          HappyWorkerItem = new global::Neon.Model.Api.Model.HappyWorkerItem();
        }
        HappyWorkerItem.MergeFrom(other.HappyWorkerItem);
      }
      if (other.changedResources_ != null) {
        if (changedResources_ == null) {
          ChangedResources = new global::Neon.Model.Api.Model.Resources();
        }
        ChangedResources.MergeFrom(other.ChangedResources);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (happyWorkerItem_ == null) {
              HappyWorkerItem = new global::Neon.Model.Api.Model.HappyWorkerItem();
            }
            input.ReadMessage(HappyWorkerItem);
            break;
          }
          case 18: {
            if (changedResources_ == null) {
              ChangedResources = new global::Neon.Model.Api.Model.Resources();
            }
            input.ReadMessage(ChangedResources);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (happyWorkerItem_ == null) {
              HappyWorkerItem = new global::Neon.Model.Api.Model.HappyWorkerItem();
            }
            input.ReadMessage(HappyWorkerItem);
            break;
          }
          case 18: {
            if (changedResources_ == null) {
              ChangedResources = new global::Neon.Model.Api.Model.Resources();
            }
            input.ReadMessage(ChangedResources);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
