// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api/item_request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Neon.Model.Api.Rpc {

  /// <summary>Holder for reflection information generated from api/item_request.proto</summary>
  public static partial class ItemRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for api/item_request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ItemRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZhcGkvaXRlbV9yZXF1ZXN0LnByb3RvEghuZW9uLmFwaRoYZXh0ZW5zaW9u",
            "L2VsaXhpcnBiLnByb3RvGhVleHRlbnNpb24vYXBpcGIucHJvdG8aG2dvb2ds",
            "ZS9wcm90b2J1Zi9lbXB0eS5wcm90bxoXbW9kZWwvZm9sbG93X3VzZXIucHJv",
            "dG8aGG1vZGVsL2l0ZW1fcmVxdWVzdC5wcm90bxoVbW9kZWwvcmVzb3VyY2Vz",
            "LnByb3RvIogBChdJdGVtUmVxdWVzdExpc3RSZXNwb25zZRIuCg1pdGVtX3Jl",
            "cXVlc3RzGAEgAygLMhcubmVvbi5tb2RlbC5JdGVtUmVxdWVzdBIlCgV1c2Vy",
            "cxgCIAMoCzIWLm5lb24ubW9kZWwuRm9sbG93VXNlchIWCg5kZWxpdmVyeV9j",
            "b3VudBgDIAEoBSJdChZJdGVtUmVxdWVzdEdldFJlc3BvbnNlEi0KDGl0ZW1f",
            "cmVxdWVzdBgBIAEoCzIXLm5lb24ubW9kZWwuSXRlbVJlcXVlc3QSFAoMaXNf",
            "cHVibGlzaGVkGAIgASgIIj0KGUl0ZW1SZXF1ZXN0UHVibGlzaFJlcXVlc3QS",
            "IAoYZGVsaXZlcnlfcmVxdWVzdF9pdGVtX2lkGAEgASgFIksKGkl0ZW1SZXF1",
            "ZXN0UHVibGlzaFJlc3BvbnNlEi0KDGl0ZW1fcmVxdWVzdBgBIAEoCzIXLm5l",
            "b24ubW9kZWwuSXRlbVJlcXVlc3QiTgoZSXRlbVJlcXVlc3RGdWxmaWxsUmVx",
            "dWVzdBIPCgd1c2VyX2lkGAEgASgDEiAKGGRlbGl2ZXJ5X3JlcXVlc3RfaXRl",
            "bV9pZBgCIAEoBSJmChpJdGVtUmVxdWVzdEZ1bGZpbGxSZXNwb25zZRIwChFj",
            "aGFuZ2VkX3Jlc291cmNlcxgBIAEoCzIVLm5lb24ubW9kZWwuUmVzb3VyY2Vz",
            "EhYKDmRlbGl2ZXJ5X2NvdW50GAIgASgFIk4KGkl0ZW1SZXF1ZXN0Q29sbGVj",
            "dFJlc3BvbnNlEjAKEWNoYW5nZWRfcmVzb3VyY2VzGAEgASgLMhUubmVvbi5t",
            "b2RlbC5SZXNvdXJjZXMy+wYKC0l0ZW1SZXF1ZXN0EqUBCgRMaXN0EhYuZ29v",
            "Z2xlLnByb3RvYnVmLkVtcHR5GiEubmVvbi5hcGkuSXRlbVJlcXVlc3RMaXN0",
            "UmVzcG9uc2UiYoK1GF4KEi9pdGVtX3JlcXVlc3QvbGlzdBJI44OV44Kp44Ot",
            "44O844GX44Gm44GE44KL44Om44O844K244O844Gu5L6d6aC85ZOB44Oq44K5",
            "44OI44KS5Y+W5b6X44GZ44KLEn4KA0dldBIWLmdvb2dsZS5wcm90b2J1Zi5F",
            "bXB0eRogLm5lb24uYXBpLkl0ZW1SZXF1ZXN0R2V0UmVzcG9uc2UiPYK1GDkK",
            "ES9pdGVtX3JlcXVlc3QvZ2V0EiTkvp3poLzjga7ntI3lk4HnirbmhYvjgpLl",
            "j5blvpfjgZnjgosSiwEKB1B1Ymxpc2gSIy5uZW9uLmFwaS5JdGVtUmVxdWVz",
            "dFB1Ymxpc2hSZXF1ZXN0GiQubmVvbi5hcGkuSXRlbVJlcXVlc3RQdWJsaXNo",
            "UmVzcG9uc2UiNYK1GDEKFS9pdGVtX3JlcXVlc3QvcHVibGlzaBIY5L6d6aC8",
            "5ZOB44KS55m76Yyy44GZ44KLEoEBCgZDYW5jZWwSFi5nb29nbGUucHJvdG9i",
            "dWYuRW1wdHkaFi5nb29nbGUucHJvdG9idWYuRW1wdHkiR4K1GEMKFC9pdGVt",
            "X3JlcXVlc3QvY2FuY2VsEhXkvp3poLzjgpLlj5bjgormtojjgZkiFGl0ZW1f",
            "cmVxdWVzdF91cGRhdGVkEqEBCgdGdWxmaWxsEiMubmVvbi5hcGkuSXRlbVJl",
            "cXVlc3RGdWxmaWxsUmVxdWVzdBokLm5lb24uYXBpLkl0ZW1SZXF1ZXN0RnVs",
            "ZmlsbFJlc3BvbnNlIkuCtRhHChUvaXRlbV9yZXF1ZXN0L2Z1bGZpbGwSGOS+",
            "nemgvOWTgeOCkue0jeWTgeOBmeOCiyIUaXRlbV9yZXF1ZXN0X3VwZGF0ZWQS",
            "jQEKB0NvbGxlY3QSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaJC5uZW9uLmFw",
            "aS5JdGVtUmVxdWVzdENvbGxlY3RSZXNwb25zZSJEgrUYQAoVL2l0ZW1fcmVx",
            "dWVzdC9jb2xsZWN0EifntI3lk4HjgZXjgozjgZ/kvp3poLzlk4HjgpLlj5fj",
            "gZHlj5bjgotCKJABAaoCEk5lb24uTW9kZWwuQXBpLlJwY7pBDQoLTmVvbi5Q",
            "Qi5BUEliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ApiClient.Extension.ElixirpbReflection.Descriptor, global::ApiClient.Extension.ApipbReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Neon.Model.Api.Model.FollowUserReflection.Descriptor, global::Neon.Model.Api.Model.ItemRequestReflection.Descriptor, global::Neon.Model.Api.Model.ResourcesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.ItemRequestListResponse), global::Neon.Model.Api.Rpc.ItemRequestListResponse.Parser, new[]{ "ItemRequests", "Users", "DeliveryCount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.ItemRequestGetResponse), global::Neon.Model.Api.Rpc.ItemRequestGetResponse.Parser, new[]{ "ItemRequest", "IsPublished" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.ItemRequestPublishRequest), global::Neon.Model.Api.Rpc.ItemRequestPublishRequest.Parser, new[]{ "DeliveryRequestItemId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.ItemRequestPublishResponse), global::Neon.Model.Api.Rpc.ItemRequestPublishResponse.Parser, new[]{ "ItemRequest" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.ItemRequestFulfillRequest), global::Neon.Model.Api.Rpc.ItemRequestFulfillRequest.Parser, new[]{ "UserId", "DeliveryRequestItemId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.ItemRequestFulfillResponse), global::Neon.Model.Api.Rpc.ItemRequestFulfillResponse.Parser, new[]{ "ChangedResources", "DeliveryCount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.ItemRequestCollectResponse), global::Neon.Model.Api.Rpc.ItemRequestCollectResponse.Parser, new[]{ "ChangedResources" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ItemRequestListResponse : pb::IMessage<ItemRequestListResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ItemRequestListResponse> _parser = new pb::MessageParser<ItemRequestListResponse>(() => new ItemRequestListResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ItemRequestListResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.ItemRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestListResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestListResponse(ItemRequestListResponse other) : this() {
      itemRequests_ = other.itemRequests_.Clone();
      users_ = other.users_.Clone();
      deliveryCount_ = other.deliveryCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestListResponse Clone() {
      return new ItemRequestListResponse(this);
    }

    /// <summary>Field number for the "item_requests" field.</summary>
    public const int ItemRequestsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Neon.Model.Api.Model.ItemRequest> _repeated_itemRequests_codec
        = pb::FieldCodec.ForMessage(10, global::Neon.Model.Api.Model.ItemRequest.Parser);
    private readonly pbc::RepeatedField<global::Neon.Model.Api.Model.ItemRequest> itemRequests_ = new pbc::RepeatedField<global::Neon.Model.Api.Model.ItemRequest>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Neon.Model.Api.Model.ItemRequest> ItemRequests {
      get { return itemRequests_; }
    }

    /// <summary>Field number for the "users" field.</summary>
    public const int UsersFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Neon.Model.Api.Model.FollowUser> _repeated_users_codec
        = pb::FieldCodec.ForMessage(18, global::Neon.Model.Api.Model.FollowUser.Parser);
    private readonly pbc::RepeatedField<global::Neon.Model.Api.Model.FollowUser> users_ = new pbc::RepeatedField<global::Neon.Model.Api.Model.FollowUser>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Neon.Model.Api.Model.FollowUser> Users {
      get { return users_; }
    }

    /// <summary>Field number for the "delivery_count" field.</summary>
    public const int DeliveryCountFieldNumber = 3;
    private int deliveryCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DeliveryCount {
      get { return deliveryCount_; }
      set {
        deliveryCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ItemRequestListResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ItemRequestListResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!itemRequests_.Equals(other.itemRequests_)) return false;
      if(!users_.Equals(other.users_)) return false;
      if (DeliveryCount != other.DeliveryCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= itemRequests_.GetHashCode();
      hash ^= users_.GetHashCode();
      if (DeliveryCount != 0) hash ^= DeliveryCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      itemRequests_.WriteTo(output, _repeated_itemRequests_codec);
      users_.WriteTo(output, _repeated_users_codec);
      if (DeliveryCount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(DeliveryCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      itemRequests_.WriteTo(ref output, _repeated_itemRequests_codec);
      users_.WriteTo(ref output, _repeated_users_codec);
      if (DeliveryCount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(DeliveryCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += itemRequests_.CalculateSize(_repeated_itemRequests_codec);
      size += users_.CalculateSize(_repeated_users_codec);
      if (DeliveryCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeliveryCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ItemRequestListResponse other) {
      if (other == null) {
        return;
      }
      itemRequests_.Add(other.itemRequests_);
      users_.Add(other.users_);
      if (other.DeliveryCount != 0) {
        DeliveryCount = other.DeliveryCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            itemRequests_.AddEntriesFrom(input, _repeated_itemRequests_codec);
            break;
          }
          case 18: {
            users_.AddEntriesFrom(input, _repeated_users_codec);
            break;
          }
          case 24: {
            DeliveryCount = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            itemRequests_.AddEntriesFrom(ref input, _repeated_itemRequests_codec);
            break;
          }
          case 18: {
            users_.AddEntriesFrom(ref input, _repeated_users_codec);
            break;
          }
          case 24: {
            DeliveryCount = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ItemRequestGetResponse : pb::IMessage<ItemRequestGetResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ItemRequestGetResponse> _parser = new pb::MessageParser<ItemRequestGetResponse>(() => new ItemRequestGetResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ItemRequestGetResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.ItemRequestReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestGetResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestGetResponse(ItemRequestGetResponse other) : this() {
      itemRequest_ = other.itemRequest_ != null ? other.itemRequest_.Clone() : null;
      isPublished_ = other.isPublished_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestGetResponse Clone() {
      return new ItemRequestGetResponse(this);
    }

    /// <summary>Field number for the "item_request" field.</summary>
    public const int ItemRequestFieldNumber = 1;
    private global::Neon.Model.Api.Model.ItemRequest itemRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Model.Api.Model.ItemRequest ItemRequest {
      get { return itemRequest_; }
      set {
        itemRequest_ = value;
      }
    }

    /// <summary>Field number for the "is_published" field.</summary>
    public const int IsPublishedFieldNumber = 2;
    private bool isPublished_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsPublished {
      get { return isPublished_; }
      set {
        isPublished_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ItemRequestGetResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ItemRequestGetResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ItemRequest, other.ItemRequest)) return false;
      if (IsPublished != other.IsPublished) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (itemRequest_ != null) hash ^= ItemRequest.GetHashCode();
      if (IsPublished != false) hash ^= IsPublished.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (itemRequest_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ItemRequest);
      }
      if (IsPublished != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsPublished);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (itemRequest_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ItemRequest);
      }
      if (IsPublished != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsPublished);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (itemRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ItemRequest);
      }
      if (IsPublished != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ItemRequestGetResponse other) {
      if (other == null) {
        return;
      }
      if (other.itemRequest_ != null) {
        if (itemRequest_ == null) {
          ItemRequest = new global::Neon.Model.Api.Model.ItemRequest();
        }
        ItemRequest.MergeFrom(other.ItemRequest);
      }
      if (other.IsPublished != false) {
        IsPublished = other.IsPublished;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (itemRequest_ == null) {
              ItemRequest = new global::Neon.Model.Api.Model.ItemRequest();
            }
            input.ReadMessage(ItemRequest);
            break;
          }
          case 16: {
            IsPublished = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (itemRequest_ == null) {
              ItemRequest = new global::Neon.Model.Api.Model.ItemRequest();
            }
            input.ReadMessage(ItemRequest);
            break;
          }
          case 16: {
            IsPublished = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ItemRequestPublishRequest : pb::IMessage<ItemRequestPublishRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ItemRequestPublishRequest> _parser = new pb::MessageParser<ItemRequestPublishRequest>(() => new ItemRequestPublishRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ItemRequestPublishRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.ItemRequestReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestPublishRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestPublishRequest(ItemRequestPublishRequest other) : this() {
      deliveryRequestItemId_ = other.deliveryRequestItemId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestPublishRequest Clone() {
      return new ItemRequestPublishRequest(this);
    }

    /// <summary>Field number for the "delivery_request_item_id" field.</summary>
    public const int DeliveryRequestItemIdFieldNumber = 1;
    private int deliveryRequestItemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DeliveryRequestItemId {
      get { return deliveryRequestItemId_; }
      set {
        deliveryRequestItemId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ItemRequestPublishRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ItemRequestPublishRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DeliveryRequestItemId != other.DeliveryRequestItemId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DeliveryRequestItemId != 0) hash ^= DeliveryRequestItemId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DeliveryRequestItemId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(DeliveryRequestItemId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DeliveryRequestItemId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(DeliveryRequestItemId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DeliveryRequestItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeliveryRequestItemId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ItemRequestPublishRequest other) {
      if (other == null) {
        return;
      }
      if (other.DeliveryRequestItemId != 0) {
        DeliveryRequestItemId = other.DeliveryRequestItemId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DeliveryRequestItemId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DeliveryRequestItemId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ItemRequestPublishResponse : pb::IMessage<ItemRequestPublishResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ItemRequestPublishResponse> _parser = new pb::MessageParser<ItemRequestPublishResponse>(() => new ItemRequestPublishResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ItemRequestPublishResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.ItemRequestReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestPublishResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestPublishResponse(ItemRequestPublishResponse other) : this() {
      itemRequest_ = other.itemRequest_ != null ? other.itemRequest_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestPublishResponse Clone() {
      return new ItemRequestPublishResponse(this);
    }

    /// <summary>Field number for the "item_request" field.</summary>
    public const int ItemRequestFieldNumber = 1;
    private global::Neon.Model.Api.Model.ItemRequest itemRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Model.Api.Model.ItemRequest ItemRequest {
      get { return itemRequest_; }
      set {
        itemRequest_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ItemRequestPublishResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ItemRequestPublishResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ItemRequest, other.ItemRequest)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (itemRequest_ != null) hash ^= ItemRequest.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (itemRequest_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ItemRequest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (itemRequest_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ItemRequest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (itemRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ItemRequest);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ItemRequestPublishResponse other) {
      if (other == null) {
        return;
      }
      if (other.itemRequest_ != null) {
        if (itemRequest_ == null) {
          ItemRequest = new global::Neon.Model.Api.Model.ItemRequest();
        }
        ItemRequest.MergeFrom(other.ItemRequest);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (itemRequest_ == null) {
              ItemRequest = new global::Neon.Model.Api.Model.ItemRequest();
            }
            input.ReadMessage(ItemRequest);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (itemRequest_ == null) {
              ItemRequest = new global::Neon.Model.Api.Model.ItemRequest();
            }
            input.ReadMessage(ItemRequest);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ItemRequestFulfillRequest : pb::IMessage<ItemRequestFulfillRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ItemRequestFulfillRequest> _parser = new pb::MessageParser<ItemRequestFulfillRequest>(() => new ItemRequestFulfillRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ItemRequestFulfillRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.ItemRequestReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestFulfillRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestFulfillRequest(ItemRequestFulfillRequest other) : this() {
      userId_ = other.userId_;
      deliveryRequestItemId_ = other.deliveryRequestItemId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestFulfillRequest Clone() {
      return new ItemRequestFulfillRequest(this);
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 1;
    private long userId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    /// <summary>Field number for the "delivery_request_item_id" field.</summary>
    public const int DeliveryRequestItemIdFieldNumber = 2;
    private int deliveryRequestItemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DeliveryRequestItemId {
      get { return deliveryRequestItemId_; }
      set {
        deliveryRequestItemId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ItemRequestFulfillRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ItemRequestFulfillRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      if (DeliveryRequestItemId != other.DeliveryRequestItemId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId != 0L) hash ^= UserId.GetHashCode();
      if (DeliveryRequestItemId != 0) hash ^= DeliveryRequestItemId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(UserId);
      }
      if (DeliveryRequestItemId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DeliveryRequestItemId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(UserId);
      }
      if (DeliveryRequestItemId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DeliveryRequestItemId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UserId);
      }
      if (DeliveryRequestItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeliveryRequestItemId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ItemRequestFulfillRequest other) {
      if (other == null) {
        return;
      }
      if (other.UserId != 0L) {
        UserId = other.UserId;
      }
      if (other.DeliveryRequestItemId != 0) {
        DeliveryRequestItemId = other.DeliveryRequestItemId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UserId = input.ReadInt64();
            break;
          }
          case 16: {
            DeliveryRequestItemId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            UserId = input.ReadInt64();
            break;
          }
          case 16: {
            DeliveryRequestItemId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ItemRequestFulfillResponse : pb::IMessage<ItemRequestFulfillResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ItemRequestFulfillResponse> _parser = new pb::MessageParser<ItemRequestFulfillResponse>(() => new ItemRequestFulfillResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ItemRequestFulfillResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.ItemRequestReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestFulfillResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestFulfillResponse(ItemRequestFulfillResponse other) : this() {
      changedResources_ = other.changedResources_ != null ? other.changedResources_.Clone() : null;
      deliveryCount_ = other.deliveryCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestFulfillResponse Clone() {
      return new ItemRequestFulfillResponse(this);
    }

    /// <summary>Field number for the "changed_resources" field.</summary>
    public const int ChangedResourcesFieldNumber = 1;
    private global::Neon.Model.Api.Model.Resources changedResources_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Model.Api.Model.Resources ChangedResources {
      get { return changedResources_; }
      set {
        changedResources_ = value;
      }
    }

    /// <summary>Field number for the "delivery_count" field.</summary>
    public const int DeliveryCountFieldNumber = 2;
    private int deliveryCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DeliveryCount {
      get { return deliveryCount_; }
      set {
        deliveryCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ItemRequestFulfillResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ItemRequestFulfillResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ChangedResources, other.ChangedResources)) return false;
      if (DeliveryCount != other.DeliveryCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (changedResources_ != null) hash ^= ChangedResources.GetHashCode();
      if (DeliveryCount != 0) hash ^= DeliveryCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (changedResources_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ChangedResources);
      }
      if (DeliveryCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DeliveryCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (changedResources_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ChangedResources);
      }
      if (DeliveryCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DeliveryCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (changedResources_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChangedResources);
      }
      if (DeliveryCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeliveryCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ItemRequestFulfillResponse other) {
      if (other == null) {
        return;
      }
      if (other.changedResources_ != null) {
        if (changedResources_ == null) {
          ChangedResources = new global::Neon.Model.Api.Model.Resources();
        }
        ChangedResources.MergeFrom(other.ChangedResources);
      }
      if (other.DeliveryCount != 0) {
        DeliveryCount = other.DeliveryCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (changedResources_ == null) {
              ChangedResources = new global::Neon.Model.Api.Model.Resources();
            }
            input.ReadMessage(ChangedResources);
            break;
          }
          case 16: {
            DeliveryCount = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (changedResources_ == null) {
              ChangedResources = new global::Neon.Model.Api.Model.Resources();
            }
            input.ReadMessage(ChangedResources);
            break;
          }
          case 16: {
            DeliveryCount = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ItemRequestCollectResponse : pb::IMessage<ItemRequestCollectResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ItemRequestCollectResponse> _parser = new pb::MessageParser<ItemRequestCollectResponse>(() => new ItemRequestCollectResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ItemRequestCollectResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.ItemRequestReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestCollectResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestCollectResponse(ItemRequestCollectResponse other) : this() {
      changedResources_ = other.changedResources_ != null ? other.changedResources_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemRequestCollectResponse Clone() {
      return new ItemRequestCollectResponse(this);
    }

    /// <summary>Field number for the "changed_resources" field.</summary>
    public const int ChangedResourcesFieldNumber = 1;
    private global::Neon.Model.Api.Model.Resources changedResources_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Model.Api.Model.Resources ChangedResources {
      get { return changedResources_; }
      set {
        changedResources_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ItemRequestCollectResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ItemRequestCollectResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ChangedResources, other.ChangedResources)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (changedResources_ != null) hash ^= ChangedResources.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (changedResources_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ChangedResources);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (changedResources_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ChangedResources);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (changedResources_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChangedResources);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ItemRequestCollectResponse other) {
      if (other == null) {
        return;
      }
      if (other.changedResources_ != null) {
        if (changedResources_ == null) {
          ChangedResources = new global::Neon.Model.Api.Model.Resources();
        }
        ChangedResources.MergeFrom(other.ChangedResources);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (changedResources_ == null) {
              ChangedResources = new global::Neon.Model.Api.Model.Resources();
            }
            input.ReadMessage(ChangedResources);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (changedResources_ == null) {
              ChangedResources = new global::Neon.Model.Api.Model.Resources();
            }
            input.ReadMessage(ChangedResources);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
