// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api/season_pass.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Neon.Model.Api.Rpc {

  /// <summary>Holder for reflection information generated from api/season_pass.proto</summary>
  public static partial class SeasonPassReflection {

    #region Descriptor
    /// <summary>File descriptor for api/season_pass.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SeasonPassReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVhcGkvc2Vhc29uX3Bhc3MucHJvdG8SCG5lb24uYXBpGhhleHRlbnNpb24v",
            "ZWxpeGlycGIucHJvdG8aFWV4dGVuc2lvbi9hcGlwYi5wcm90bxoYZXh0ZW5z",
            "aW9uL3ZhbGlkYXRlLnByb3RvGhthcGkvY2hhbmdlZF9yZXNvdXJjZXMucHJv",
            "dG8aFW1vZGVsL3Jlc291cmNlcy5wcm90bxoSbW9kZWwvcmV3YXJkLnByb3Rv",
            "IowBChhTZWFzb25QYXNzUmVjZWl2ZVJlcXVlc3QSGgoJc2Vhc29uX2lkGAEg",
            "ASgFQgf6QgQaAigBEiQKE3NlYXNvbl9wYXNzX3RpZXJfaWQYAiABKAVCB/pC",
            "BBoCKAESLgoQc2Vhc29uX3Bhc3NfdHlwZRgDIAEoBUIUorsYEAoOU2Vhc29u",
            "UGFzc1R5cGUicgoZU2Vhc29uUGFzc1JlY2VpdmVSZXNwb25zZRIwChFjaGFu",
            "Z2VkX3Jlc291cmNlcxgBIAEoCzIVLm5lb24ubW9kZWwuUmVzb3VyY2VzEiMK",
            "B3Jld2FyZHMYAiADKAsyEi5uZW9uLm1vZGVsLlJld2FyZCI5ChtTZWFzb25Q",
            "YXNzUmVjZWl2ZUFsbFJlcXVlc3QSGgoJc2Vhc29uX2lkGAEgASgFQgf6QgQa",
            "AigBInUKHFNlYXNvblBhc3NSZWNlaXZlQWxsUmVzcG9uc2USMAoRY2hhbmdl",
            "ZF9yZXNvdXJjZXMYASABKAsyFS5uZW9uLm1vZGVsLlJlc291cmNlcxIjCgdy",
            "ZXdhcmRzGAIgAygLMhIubmVvbi5tb2RlbC5SZXdhcmQiXAodU2Vhc29uUGFz",
            "c1RpZXJQdXJjaGFzZVJlcXVlc3QSGgoJc2Vhc29uX2lkGAEgASgFQgf6QgQa",
            "AigBEh8KDnB1cmNoYXNlX2NvdW50GAIgASgFQgf6QgQaAigBIk4KIVNlYXNv",
            "blBhc3NQdXJjaGFzZVBhaWRQYXNzUmVxdWVzdBIRCglzZWFzb25faWQYASAB",
            "KAUSFgoOcHVyY2hhc2VfdXBwZXIYAiABKAgiewoiU2Vhc29uUGFzc1B1cmNo",
            "YXNlUGFpZFBhc3NSZXNwb25zZRIwChFjaGFuZ2VkX3Jlc291cmNlcxgBIAEo",
            "CzIVLm5lb24ubW9kZWwuUmVzb3VyY2VzEiMKB3Jld2FyZHMYAiADKAsyEi5u",
            "ZW9uLm1vZGVsLlJld2FyZDLJBgoKU2Vhc29uUGFzcxK+AQoHUmVjZWl2ZRIi",
            "Lm5lb24uYXBpLlNlYXNvblBhc3NSZWNlaXZlUmVxdWVzdBojLm5lb24uYXBp",
            "LlNlYXNvblBhc3NSZWNlaXZlUmVzcG9uc2UiaoK1GGYKFC9zZWFzb25fcGFz",
            "cy9yZWNlaXZlEirjgrfjg7zjgrrjg7Pjg5Hjgrnjga7loLHphazjgpLlj5fj",
            "gZHlj5bjgosiD291dF9vZl9zY2hlZHVsZSIRcmV3YXJkX292ZXJmbG93ZWQS",
            "6AEKClJlY2VpdmVBbGwSJS5uZW9uLmFwaS5TZWFzb25QYXNzUmVjZWl2ZUFs",
            "bFJlcXVlc3QaJi5uZW9uLmFwaS5TZWFzb25QYXNzUmVjZWl2ZUFsbFJlc3Bv",
            "bnNlIooBgrUYhQEKGC9zZWFzb25fcGFzcy9yZWNlaXZlX2FsbBJF5pyq5Y+X",
            "44GR5Y+W44KK44Gu44K344O844K644Oz44OR44K544Gu5aCx6YWs44GZ44G5",
            "44Gm44KS5Y+X44GR5Y+W44KLIg9vdXRfb2Zfc2NoZWR1bGUiEXJld2FyZF9v",
            "dmVyZmxvd2VkEr0BCgxUaWVyUHVyY2hhc2USJy5uZW9uLmFwaS5TZWFzb25Q",
            "YXNzVGllclB1cmNoYXNlUmVxdWVzdBoiLm5lb24uYXBpLkNoYW5nZWRSZXNv",
            "dXJjZXNSZXNwb25zZSJggrUYXAoaL3NlYXNvbl9wYXNzL3RpZXJfcHVyY2hh",
            "c2USLeOCt+ODvOOCuuODs+ODkeOCueOBruODhuOCo+OCouOCkuizvOWFpeOB",
            "meOCiyIPb3V0X29mX3NjaGVkdWxlEs4BChBQdXJjaGFzZVBhaWRQYXNzEisu",
            "bmVvbi5hcGkuU2Vhc29uUGFzc1B1cmNoYXNlUGFpZFBhc3NSZXF1ZXN0Giwu",
            "bmVvbi5hcGkuU2Vhc29uUGFzc1B1cmNoYXNlUGFpZFBhc3NSZXNwb25zZSJf",
            "grUYWwofL3NlYXNvbl9wYXNzL3B1cmNoYXNlX3BhaWRfcGFzcxIn5pyJ5YSf",
            "44K344O844K644Oz44OR44K544KS6LO85YWl44GZ44KLIg9vdXRfb2Zfc2No",
            "ZWR1bGVCKJABAaoCEk5lb24uTW9kZWwuQXBpLlJwY7pBDQoLTmVvbi5QQi5B",
            "UEliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ApiClient.Extension.ElixirpbReflection.Descriptor, global::ApiClient.Extension.ApipbReflection.Descriptor, global::ApiClient.Extension.ValidateReflection.Descriptor, global::Neon.Model.Api.Rpc.ChangedResourcesReflection.Descriptor, global::Neon.Model.Api.Model.ResourcesReflection.Descriptor, global::Neon.Model.Api.Model.RewardReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.SeasonPassReceiveRequest), global::Neon.Model.Api.Rpc.SeasonPassReceiveRequest.Parser, new[]{ "SeasonId", "SeasonPassTierId", "SeasonPassType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.SeasonPassReceiveResponse), global::Neon.Model.Api.Rpc.SeasonPassReceiveResponse.Parser, new[]{ "ChangedResources", "Rewards" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.SeasonPassReceiveAllRequest), global::Neon.Model.Api.Rpc.SeasonPassReceiveAllRequest.Parser, new[]{ "SeasonId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.SeasonPassReceiveAllResponse), global::Neon.Model.Api.Rpc.SeasonPassReceiveAllResponse.Parser, new[]{ "ChangedResources", "Rewards" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.SeasonPassTierPurchaseRequest), global::Neon.Model.Api.Rpc.SeasonPassTierPurchaseRequest.Parser, new[]{ "SeasonId", "PurchaseCount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.SeasonPassPurchasePaidPassRequest), global::Neon.Model.Api.Rpc.SeasonPassPurchasePaidPassRequest.Parser, new[]{ "SeasonId", "PurchaseUpper" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Neon.Model.Api.Rpc.SeasonPassPurchasePaidPassResponse), global::Neon.Model.Api.Rpc.SeasonPassPurchasePaidPassResponse.Parser, new[]{ "ChangedResources", "Rewards" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SeasonPassReceiveRequest : pb::IMessage<SeasonPassReceiveRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SeasonPassReceiveRequest> _parser = new pb::MessageParser<SeasonPassReceiveRequest>(() => new SeasonPassReceiveRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SeasonPassReceiveRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.SeasonPassReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassReceiveRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassReceiveRequest(SeasonPassReceiveRequest other) : this() {
      seasonId_ = other.seasonId_;
      seasonPassTierId_ = other.seasonPassTierId_;
      seasonPassType_ = other.seasonPassType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassReceiveRequest Clone() {
      return new SeasonPassReceiveRequest(this);
    }

    /// <summary>Field number for the "season_id" field.</summary>
    public const int SeasonIdFieldNumber = 1;
    private int seasonId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SeasonId {
      get { return seasonId_; }
      set {
        seasonId_ = value;
      }
    }

    /// <summary>Field number for the "season_pass_tier_id" field.</summary>
    public const int SeasonPassTierIdFieldNumber = 2;
    private int seasonPassTierId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SeasonPassTierId {
      get { return seasonPassTierId_; }
      set {
        seasonPassTierId_ = value;
      }
    }

    /// <summary>Field number for the "season_pass_type" field.</summary>
    public const int SeasonPassTypeFieldNumber = 3;
    private int seasonPassType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SeasonPassType {
      get { return seasonPassType_; }
      set {
        seasonPassType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SeasonPassReceiveRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SeasonPassReceiveRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SeasonId != other.SeasonId) return false;
      if (SeasonPassTierId != other.SeasonPassTierId) return false;
      if (SeasonPassType != other.SeasonPassType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SeasonId != 0) hash ^= SeasonId.GetHashCode();
      if (SeasonPassTierId != 0) hash ^= SeasonPassTierId.GetHashCode();
      if (SeasonPassType != 0) hash ^= SeasonPassType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SeasonId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SeasonId);
      }
      if (SeasonPassTierId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SeasonPassTierId);
      }
      if (SeasonPassType != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SeasonPassType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SeasonId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SeasonId);
      }
      if (SeasonPassTierId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SeasonPassTierId);
      }
      if (SeasonPassType != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SeasonPassType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SeasonId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeasonId);
      }
      if (SeasonPassTierId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeasonPassTierId);
      }
      if (SeasonPassType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeasonPassType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SeasonPassReceiveRequest other) {
      if (other == null) {
        return;
      }
      if (other.SeasonId != 0) {
        SeasonId = other.SeasonId;
      }
      if (other.SeasonPassTierId != 0) {
        SeasonPassTierId = other.SeasonPassTierId;
      }
      if (other.SeasonPassType != 0) {
        SeasonPassType = other.SeasonPassType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SeasonId = input.ReadInt32();
            break;
          }
          case 16: {
            SeasonPassTierId = input.ReadInt32();
            break;
          }
          case 24: {
            SeasonPassType = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SeasonId = input.ReadInt32();
            break;
          }
          case 16: {
            SeasonPassTierId = input.ReadInt32();
            break;
          }
          case 24: {
            SeasonPassType = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SeasonPassReceiveResponse : pb::IMessage<SeasonPassReceiveResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SeasonPassReceiveResponse> _parser = new pb::MessageParser<SeasonPassReceiveResponse>(() => new SeasonPassReceiveResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SeasonPassReceiveResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.SeasonPassReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassReceiveResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassReceiveResponse(SeasonPassReceiveResponse other) : this() {
      changedResources_ = other.changedResources_ != null ? other.changedResources_.Clone() : null;
      rewards_ = other.rewards_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassReceiveResponse Clone() {
      return new SeasonPassReceiveResponse(this);
    }

    /// <summary>Field number for the "changed_resources" field.</summary>
    public const int ChangedResourcesFieldNumber = 1;
    private global::Neon.Model.Api.Model.Resources changedResources_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Model.Api.Model.Resources ChangedResources {
      get { return changedResources_; }
      set {
        changedResources_ = value;
      }
    }

    /// <summary>Field number for the "rewards" field.</summary>
    public const int RewardsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Neon.Model.Api.Model.Reward> _repeated_rewards_codec
        = pb::FieldCodec.ForMessage(18, global::Neon.Model.Api.Model.Reward.Parser);
    private readonly pbc::RepeatedField<global::Neon.Model.Api.Model.Reward> rewards_ = new pbc::RepeatedField<global::Neon.Model.Api.Model.Reward>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Neon.Model.Api.Model.Reward> Rewards {
      get { return rewards_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SeasonPassReceiveResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SeasonPassReceiveResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ChangedResources, other.ChangedResources)) return false;
      if(!rewards_.Equals(other.rewards_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (changedResources_ != null) hash ^= ChangedResources.GetHashCode();
      hash ^= rewards_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (changedResources_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ChangedResources);
      }
      rewards_.WriteTo(output, _repeated_rewards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (changedResources_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ChangedResources);
      }
      rewards_.WriteTo(ref output, _repeated_rewards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (changedResources_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChangedResources);
      }
      size += rewards_.CalculateSize(_repeated_rewards_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SeasonPassReceiveResponse other) {
      if (other == null) {
        return;
      }
      if (other.changedResources_ != null) {
        if (changedResources_ == null) {
          ChangedResources = new global::Neon.Model.Api.Model.Resources();
        }
        ChangedResources.MergeFrom(other.ChangedResources);
      }
      rewards_.Add(other.rewards_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (changedResources_ == null) {
              ChangedResources = new global::Neon.Model.Api.Model.Resources();
            }
            input.ReadMessage(ChangedResources);
            break;
          }
          case 18: {
            rewards_.AddEntriesFrom(input, _repeated_rewards_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (changedResources_ == null) {
              ChangedResources = new global::Neon.Model.Api.Model.Resources();
            }
            input.ReadMessage(ChangedResources);
            break;
          }
          case 18: {
            rewards_.AddEntriesFrom(ref input, _repeated_rewards_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SeasonPassReceiveAllRequest : pb::IMessage<SeasonPassReceiveAllRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SeasonPassReceiveAllRequest> _parser = new pb::MessageParser<SeasonPassReceiveAllRequest>(() => new SeasonPassReceiveAllRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SeasonPassReceiveAllRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.SeasonPassReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassReceiveAllRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassReceiveAllRequest(SeasonPassReceiveAllRequest other) : this() {
      seasonId_ = other.seasonId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassReceiveAllRequest Clone() {
      return new SeasonPassReceiveAllRequest(this);
    }

    /// <summary>Field number for the "season_id" field.</summary>
    public const int SeasonIdFieldNumber = 1;
    private int seasonId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SeasonId {
      get { return seasonId_; }
      set {
        seasonId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SeasonPassReceiveAllRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SeasonPassReceiveAllRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SeasonId != other.SeasonId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SeasonId != 0) hash ^= SeasonId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SeasonId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SeasonId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SeasonId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SeasonId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SeasonId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeasonId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SeasonPassReceiveAllRequest other) {
      if (other == null) {
        return;
      }
      if (other.SeasonId != 0) {
        SeasonId = other.SeasonId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SeasonId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SeasonId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SeasonPassReceiveAllResponse : pb::IMessage<SeasonPassReceiveAllResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SeasonPassReceiveAllResponse> _parser = new pb::MessageParser<SeasonPassReceiveAllResponse>(() => new SeasonPassReceiveAllResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SeasonPassReceiveAllResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.SeasonPassReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassReceiveAllResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassReceiveAllResponse(SeasonPassReceiveAllResponse other) : this() {
      changedResources_ = other.changedResources_ != null ? other.changedResources_.Clone() : null;
      rewards_ = other.rewards_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassReceiveAllResponse Clone() {
      return new SeasonPassReceiveAllResponse(this);
    }

    /// <summary>Field number for the "changed_resources" field.</summary>
    public const int ChangedResourcesFieldNumber = 1;
    private global::Neon.Model.Api.Model.Resources changedResources_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Model.Api.Model.Resources ChangedResources {
      get { return changedResources_; }
      set {
        changedResources_ = value;
      }
    }

    /// <summary>Field number for the "rewards" field.</summary>
    public const int RewardsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Neon.Model.Api.Model.Reward> _repeated_rewards_codec
        = pb::FieldCodec.ForMessage(18, global::Neon.Model.Api.Model.Reward.Parser);
    private readonly pbc::RepeatedField<global::Neon.Model.Api.Model.Reward> rewards_ = new pbc::RepeatedField<global::Neon.Model.Api.Model.Reward>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Neon.Model.Api.Model.Reward> Rewards {
      get { return rewards_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SeasonPassReceiveAllResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SeasonPassReceiveAllResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ChangedResources, other.ChangedResources)) return false;
      if(!rewards_.Equals(other.rewards_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (changedResources_ != null) hash ^= ChangedResources.GetHashCode();
      hash ^= rewards_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (changedResources_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ChangedResources);
      }
      rewards_.WriteTo(output, _repeated_rewards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (changedResources_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ChangedResources);
      }
      rewards_.WriteTo(ref output, _repeated_rewards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (changedResources_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChangedResources);
      }
      size += rewards_.CalculateSize(_repeated_rewards_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SeasonPassReceiveAllResponse other) {
      if (other == null) {
        return;
      }
      if (other.changedResources_ != null) {
        if (changedResources_ == null) {
          ChangedResources = new global::Neon.Model.Api.Model.Resources();
        }
        ChangedResources.MergeFrom(other.ChangedResources);
      }
      rewards_.Add(other.rewards_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (changedResources_ == null) {
              ChangedResources = new global::Neon.Model.Api.Model.Resources();
            }
            input.ReadMessage(ChangedResources);
            break;
          }
          case 18: {
            rewards_.AddEntriesFrom(input, _repeated_rewards_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (changedResources_ == null) {
              ChangedResources = new global::Neon.Model.Api.Model.Resources();
            }
            input.ReadMessage(ChangedResources);
            break;
          }
          case 18: {
            rewards_.AddEntriesFrom(ref input, _repeated_rewards_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SeasonPassTierPurchaseRequest : pb::IMessage<SeasonPassTierPurchaseRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SeasonPassTierPurchaseRequest> _parser = new pb::MessageParser<SeasonPassTierPurchaseRequest>(() => new SeasonPassTierPurchaseRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SeasonPassTierPurchaseRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.SeasonPassReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassTierPurchaseRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassTierPurchaseRequest(SeasonPassTierPurchaseRequest other) : this() {
      seasonId_ = other.seasonId_;
      purchaseCount_ = other.purchaseCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassTierPurchaseRequest Clone() {
      return new SeasonPassTierPurchaseRequest(this);
    }

    /// <summary>Field number for the "season_id" field.</summary>
    public const int SeasonIdFieldNumber = 1;
    private int seasonId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SeasonId {
      get { return seasonId_; }
      set {
        seasonId_ = value;
      }
    }

    /// <summary>Field number for the "purchase_count" field.</summary>
    public const int PurchaseCountFieldNumber = 2;
    private int purchaseCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PurchaseCount {
      get { return purchaseCount_; }
      set {
        purchaseCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SeasonPassTierPurchaseRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SeasonPassTierPurchaseRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SeasonId != other.SeasonId) return false;
      if (PurchaseCount != other.PurchaseCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SeasonId != 0) hash ^= SeasonId.GetHashCode();
      if (PurchaseCount != 0) hash ^= PurchaseCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SeasonId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SeasonId);
      }
      if (PurchaseCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PurchaseCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SeasonId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SeasonId);
      }
      if (PurchaseCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PurchaseCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SeasonId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeasonId);
      }
      if (PurchaseCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PurchaseCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SeasonPassTierPurchaseRequest other) {
      if (other == null) {
        return;
      }
      if (other.SeasonId != 0) {
        SeasonId = other.SeasonId;
      }
      if (other.PurchaseCount != 0) {
        PurchaseCount = other.PurchaseCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SeasonId = input.ReadInt32();
            break;
          }
          case 16: {
            PurchaseCount = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SeasonId = input.ReadInt32();
            break;
          }
          case 16: {
            PurchaseCount = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SeasonPassPurchasePaidPassRequest : pb::IMessage<SeasonPassPurchasePaidPassRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SeasonPassPurchasePaidPassRequest> _parser = new pb::MessageParser<SeasonPassPurchasePaidPassRequest>(() => new SeasonPassPurchasePaidPassRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SeasonPassPurchasePaidPassRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.SeasonPassReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassPurchasePaidPassRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassPurchasePaidPassRequest(SeasonPassPurchasePaidPassRequest other) : this() {
      seasonId_ = other.seasonId_;
      purchaseUpper_ = other.purchaseUpper_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassPurchasePaidPassRequest Clone() {
      return new SeasonPassPurchasePaidPassRequest(this);
    }

    /// <summary>Field number for the "season_id" field.</summary>
    public const int SeasonIdFieldNumber = 1;
    private int seasonId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SeasonId {
      get { return seasonId_; }
      set {
        seasonId_ = value;
      }
    }

    /// <summary>Field number for the "purchase_upper" field.</summary>
    public const int PurchaseUpperFieldNumber = 2;
    private bool purchaseUpper_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool PurchaseUpper {
      get { return purchaseUpper_; }
      set {
        purchaseUpper_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SeasonPassPurchasePaidPassRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SeasonPassPurchasePaidPassRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SeasonId != other.SeasonId) return false;
      if (PurchaseUpper != other.PurchaseUpper) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SeasonId != 0) hash ^= SeasonId.GetHashCode();
      if (PurchaseUpper != false) hash ^= PurchaseUpper.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SeasonId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SeasonId);
      }
      if (PurchaseUpper != false) {
        output.WriteRawTag(16);
        output.WriteBool(PurchaseUpper);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SeasonId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SeasonId);
      }
      if (PurchaseUpper != false) {
        output.WriteRawTag(16);
        output.WriteBool(PurchaseUpper);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SeasonId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeasonId);
      }
      if (PurchaseUpper != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SeasonPassPurchasePaidPassRequest other) {
      if (other == null) {
        return;
      }
      if (other.SeasonId != 0) {
        SeasonId = other.SeasonId;
      }
      if (other.PurchaseUpper != false) {
        PurchaseUpper = other.PurchaseUpper;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SeasonId = input.ReadInt32();
            break;
          }
          case 16: {
            PurchaseUpper = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SeasonId = input.ReadInt32();
            break;
          }
          case 16: {
            PurchaseUpper = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SeasonPassPurchasePaidPassResponse : pb::IMessage<SeasonPassPurchasePaidPassResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SeasonPassPurchasePaidPassResponse> _parser = new pb::MessageParser<SeasonPassPurchasePaidPassResponse>(() => new SeasonPassPurchasePaidPassResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SeasonPassPurchasePaidPassResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Neon.Model.Api.Rpc.SeasonPassReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassPurchasePaidPassResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassPurchasePaidPassResponse(SeasonPassPurchasePaidPassResponse other) : this() {
      changedResources_ = other.changedResources_ != null ? other.changedResources_.Clone() : null;
      rewards_ = other.rewards_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SeasonPassPurchasePaidPassResponse Clone() {
      return new SeasonPassPurchasePaidPassResponse(this);
    }

    /// <summary>Field number for the "changed_resources" field.</summary>
    public const int ChangedResourcesFieldNumber = 1;
    private global::Neon.Model.Api.Model.Resources changedResources_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Neon.Model.Api.Model.Resources ChangedResources {
      get { return changedResources_; }
      set {
        changedResources_ = value;
      }
    }

    /// <summary>Field number for the "rewards" field.</summary>
    public const int RewardsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Neon.Model.Api.Model.Reward> _repeated_rewards_codec
        = pb::FieldCodec.ForMessage(18, global::Neon.Model.Api.Model.Reward.Parser);
    private readonly pbc::RepeatedField<global::Neon.Model.Api.Model.Reward> rewards_ = new pbc::RepeatedField<global::Neon.Model.Api.Model.Reward>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Neon.Model.Api.Model.Reward> Rewards {
      get { return rewards_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SeasonPassPurchasePaidPassResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SeasonPassPurchasePaidPassResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ChangedResources, other.ChangedResources)) return false;
      if(!rewards_.Equals(other.rewards_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (changedResources_ != null) hash ^= ChangedResources.GetHashCode();
      hash ^= rewards_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (changedResources_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ChangedResources);
      }
      rewards_.WriteTo(output, _repeated_rewards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (changedResources_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ChangedResources);
      }
      rewards_.WriteTo(ref output, _repeated_rewards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (changedResources_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChangedResources);
      }
      size += rewards_.CalculateSize(_repeated_rewards_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SeasonPassPurchasePaidPassResponse other) {
      if (other == null) {
        return;
      }
      if (other.changedResources_ != null) {
        if (changedResources_ == null) {
          ChangedResources = new global::Neon.Model.Api.Model.Resources();
        }
        ChangedResources.MergeFrom(other.ChangedResources);
      }
      rewards_.Add(other.rewards_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (changedResources_ == null) {
              ChangedResources = new global::Neon.Model.Api.Model.Resources();
            }
            input.ReadMessage(ChangedResources);
            break;
          }
          case 18: {
            rewards_.AddEntriesFrom(input, _repeated_rewards_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (changedResources_ == null) {
              ChangedResources = new global::Neon.Model.Api.Model.Resources();
            }
            input.ReadMessage(ChangedResources);
            break;
          }
          case 18: {
            rewards_.AddEntriesFrom(ref input, _repeated_rewards_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
