name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    environment:
      name: MYENV

    steps:
    - uses: actions/checkout@v4

    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: '2.2.4'

    - name: Meson dummy
      uses: BSFishy/meson-build@v1.0.3
      with:
        meson-version: 1.8.1
        action: test
        directory: bin/build_dummy

    - name: Build everything
      run: python build.py

    - name: Compress files
      run: cd bin/Release/net9.0/publish && 7z a sembastandalone-${{ github.ref_name }}-x64.zip *

    - name: Upload Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/Release/net9.0/publish/sembastandalone-${{ github.ref_name }}-x64.zip
        tag: ${{ github.ref }}
        overwrite: true
